# Rhythmx — Sprint 4: Pretrained Embedding Extraction
### CNN (baseline, from Sprint 3) vs. musicnn vs. MERT

This notebook extracts embeddings from two pretrained audio models — **musicnn**
(music-specific auto-tagging CNN) and **MERT** (self-supervised music foundation model)
— for the same GTZAN clips used to train `GenreCNN`. These embeddings feed lightweight
classifier heads in the companion workflow doc (`Sprint4_Comparison_Workflow.md`),
so we can benchmark our from-scratch CNN against transfer-learning baselines on
identical train/val/test splits.

**Outputs of this notebook:**
- `embeddings/musicnn_{split}.npy` + `embeddings/musicnn_{split}_labels.csv`
- `embeddings/mert_{split}.npy` + `embeddings/mert_{split}_labels.csv`
- `embeddings/extraction_timing.csv` (for the cost-comparison table in Sprint 4)

**Prerequisite:** run this against the exact same file list / split as `CNN_Training.ipynb`
so results are directly comparable. Do not re-split randomly here.

## 1. Environment setup

musicnn is TensorFlow-based; MERT is PyTorch/HuggingFace-based. Rather than fight
dependency conflicts inside your existing `DS_class` conda env (which is tuned for
your PyTorch CNN pipeline), create an isolated env just for embedding extraction.
Run this in your WSL2 Ubuntu terminal:

```bash
conda create -n rhythmx_embed python=3.10 -y
conda activate rhythmx_embed

# musicnn dependency pin (numpy<1.17,>=1.14.5); those numpy versions are incompatible with Python 3.10
# Python 3.10 and other newer packages don't have the distutils/ccompiler.py those older numpy versions depend on
# musicnn (TF-based auto-tagger)
pip install musicnn --no-deps
pip install "numpy>=1.19,<1.24" "tensorflow==3.15.0.post1"

# MERT (HuggingFace)
pip install transformers torch torchaudio accelerate soxr

# shared utilities
pip install "librosa>=0.7.0,<0.9" soundfile audioread pandas numpy scikit-learn psycopg2-binary tqdm "setuptools<81"

# register the env as a Jupyter kernel
pip install ipykernel
python -m ipykernel install --user --name rhythmx_embed --display-name "Python (rhythmx_embed)"
```

Then select the **Python (rhythmx_embed)** kernel for this notebook in VS Code
before running the cells below.

> Note: MERT-v1-330M is ~330M params and will be slow on CPU. If you don't have GPU
> access in WSL2 (check with `nvidia-smi`), switch to `m-a-p/MERT-v1-95M` below —
> it's noted inline as a swap-in.

In [ ]:
import os
import time
import json
import numpy as np
import pandas as pd
import librosa
import torch
from tqdm import tqdm

print("cwd:", os.getcwd())
print("files here:", sorted((os.listdir('.'))))
print("model.py present?", 'model.py' in os.listdir('.'))

# musicnn
from musicnn.extractor import extractor as musicnn_extractor

# MERT
from transformers import Wav2Vec2FeatureExtractor, AutoModel
print("transformers audio imports OK")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/librosa/util/files.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

cwd: /mnt/c/Users/winni/music-genre-class/music-genre-classification/Code
files here: ['CNN_Training.ipynb', 'EDA.ipynb', 'Sprint4_Embedding_Extraction.ipynb', '__pycache__', 'api_app_genre.py', 'best_genre_cnn.pt', 'clean-preprocess.ipynb', 'embeddings', 'mert_setup_notes.txt', 'model.py', 'preprocess_clean_final.ipynb', 'streamlit_app_genre.py']
model.py present? True

2026-07-12 11:01:08.003647: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-12 11:01:08.243951: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-07-12 11:01:08.838088: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-07-12 11:01:08.838153: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-07-12 11:01:08.867744: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-07-12 11:01:08.981559: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-07-12 11:01:08.983069: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-12 11:01:11.465639: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

transformers audio imports OK
Using device: cpu

## 2. Load the exact same train/val/test split used for `GenreCNN`

Point this at whatever your CNN notebook used as the source of truth — either the
`vw_clean_tracks` Postgres view (if the split/fold was persisted there) or a saved
CSV of file paths + labels + split assignment. **Do not regenerate the split here.**

Adjust the query/path below to match your actual Sprint 3 setup.

In [ ]:
# Pull from Postgres (music_genre_db) ---
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    dbname="music_genre_db",
    user="postgres",          # adjust to your WSL2 Postgres user
    password=os.environ.get("PGPASSWORD", ""),
    port=5432,
)

query = """
    SELECT track_id, file_path, label AS genre, split
    FROM vw_clean_tracks
    WHERE split IN ('train', 'val', 'test')
    ORDER BY track_id
"""
tracks_df = pd.read_sql(query, conn)
conn.close()

tracks_df.head()

split_counts = tracks_df["split"].value_counts()
print(split_counts)

# Sanity check against Sprint 3's known split sizes
expected_counts = {"train": 677, "val": 141, "test": 153}
for split_name, expected_n in expected_counts.items():
    actual_n = split_counts.get(split_name, 0)
    assert actual_n == expected_n, (
        f"Split mismatch for '{split_name}': expected {expected_n}, got {actual_n}. "
        "vw_clean_tracks may have changed since Sprint 3 — investigate before extracting embeddings."
    )

print("Split counts match Sprint 3 exactly — safe to proceed.")
tracks_df.head()

split
train    677
test     153
val      141
Name: count, dtype: int64
Split counts match Sprint 3 exactly — safe to proceed.

/tmp/ipykernel_75943/1076542290.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tracks_df = pd.read_sql(query, conn)

   track_id                                      file_path  genre  split
0         1  ../Data_Music/processed/blues/blues.00000.wav  blues    val
1         2  ../Data_Music/processed/blues/blues.00001.wav  blues  train
2         3  ../Data_Music/processed/blues/blues.00002.wav  blues  train
3         4  ../Data_Music/processed/blues/blues.00003.wav  blues   test
4         5  ../Data_Music/processed/blues/blues.00004.wav  blues   test

## 3. musicnn embedding extraction

`musicnn.extractor` returns penultimate-layer features per clip (taggram + pooled
embedding). We use the pooled `features['mean_pool']` (or `features['max_pool']`)
representation as our fixed-length embedding — 200-dim for the `MSD_musicnn` model,
753-dim for the `MTT_musicnn` model. `MSD_musicnn` (trained on the Million Song
Dataset) is the closer match to a genre-classification task; start there.

In [ ]:
def extract_musicnn_embedding(file_path, model="MSD_musicnn"):
    """Return a single fixed-length embedding vector for one audio clip."""
    taggram, tags, features = musicnn_extractor(
        file_path, model=model, extract_features=True
    )
    # mean_pool: (n_frames, 200) -> average over time for a clip-level vector
    embedding = features["mean_pool"].mean(axis=0)
    return embedding


def extract_musicnn_split(df, split_name, out_dir="embeddings"):
    os.makedirs(out_dir, exist_ok=True)
    split_df = df[df["split"] == split_name].reset_index(drop=True)

    embeddings = []
    labels = []
    failures = []
    start = time.time()

    for _, row in tqdm(split_df.iterrows(), total=len(split_df), desc=f"musicnn:{split_name}"):
        try:
            emb = extract_musicnn_embedding(row["file_path"])
            embeddings.append(emb)
            labels.append(row["genre"])
        except Exception as e:
            failures.append((row["file_path"], str(e)))

    elapsed = time.time() - start
    embeddings = np.stack(embeddings)

    np.save(f"{out_dir}/musicnn_{split_name}.npy", embeddings)
    pd.DataFrame({"genre": labels}).to_csv(
        f"{out_dir}/musicnn_{split_name}_labels.csv", index=False
    )

    if failures:
        print(f"  {len(failures)} clips failed extraction — see failures list")

    return {
        "model": "musicnn",
        "split": split_name,
        "n_clips": len(embeddings),
        "embedding_dim": embeddings.shape[1],
        "total_seconds": elapsed,
        "seconds_per_clip": elapsed / max(len(embeddings), 1),
        "n_failures": len(failures),
    }


musicnn_timing = []
for split in ["train", "val", "test"]:
    musicnn_timing.append(extract_musicnn_split(tracks_df, split))

pd.DataFrame(musicnn_timing)

musicnn:train:   0%|          | 0/677 [00:00<?, ?it/s]

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:58: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  normalized_input = tf.compat.v1.layers.batch_normalization(expand_input, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:103: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:108: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:109: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:117: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:122: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:123: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:135: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv1 = tf.compat.v1.layers.conv2d(inputs=front_end_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:140: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv1 = tf.compat.v1.layers.batch_normalization(conv1, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:145: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv2 = tf.compat.v1.layers.conv2d(inputs=bn_conv1_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:150: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv2 = tf.compat.v1.layers.batch_normalization(conv2, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:156: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv3 = tf.compat.v1.layers.conv2d(inputs=bn_conv2_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:161: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv3 = tf.compat.v1.layers.batch_normalization(conv3, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:176: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  flat_pool = tf.compat.v1.layers.flatten(tmp_pool)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:177: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  flat_pool = tf.compat.v1.layers.batch_normalization(flat_pool, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:178: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  flat_pool_dropout = tf.compat.v1.layers.dropout(flat_pool, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:179: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  dense = tf.compat.v1.layers.dense(inputs=flat_pool_dropout,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:182: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_dense = tf.compat.v1.layers.batch_normalization(dense, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:183: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  dense_dropout = tf.compat.v1.layers.dropout(bn_dense, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:186: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  logits = tf.compat.v1.layers.dense(inputs=dense_dropout,
2026-07-12 11:01:47.604082: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 1/677 [00:03<34:24,  3.05s/it]

done!

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:58: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  normalized_input = tf.compat.v1.layers.batch_normalization(expand_input, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:103: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:108: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:109: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:117: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:122: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:123: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:135: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv1 = tf.compat.v1.layers.conv2d(inputs=front_end_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:140: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv1 = tf.compat.v1.layers.batch_normalization(conv1, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:145: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv2 = tf.compat.v1.layers.conv2d(inputs=bn_conv1_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:150: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv2 = tf.compat.v1.layers.batch_normalization(conv2, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:156: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv3 = tf.compat.v1.layers.conv2d(inputs=bn_conv2_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:161: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv3 = tf.compat.v1.layers.batch_normalization(conv3, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:176: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  flat_pool = tf.compat.v1.layers.flatten(tmp_pool)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:177: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  flat_pool = tf.compat.v1.layers.batch_normalization(flat_pool, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:178: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  flat_pool_dropout = tf.compat.v1.layers.dropout(flat_pool, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:179: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  dense = tf.compat.v1.layers.dense(inputs=flat_pool_dropout,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:182: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_dense = tf.compat.v1.layers.batch_normalization(dense, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:183: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  dense_dropout = tf.compat.v1.layers.dropout(bn_dense, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:186: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  logits = tf.compat.v1.layers.dense(inputs=dense_dropout,

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 2/677 [00:04<26:37,  2.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 3/677 [00:06<24:27,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 4/677 [00:09<26:39,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 5/677 [00:11<26:47,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 6/677 [00:14<25:25,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 7/677 [00:17<29:29,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 8/677 [00:20<30:18,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|▏         | 9/677 [00:22<29:32,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|▏         | 10/677 [00:25<29:19,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 11/677 [00:28<29:54,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 12/677 [00:30<28:37,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 13/677 [00:32<26:50,  2.43s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 14/677 [00:34<25:50,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 15/677 [00:37<25:39,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 16/677 [00:39<26:37,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 17/677 [00:42<26:23,  2.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 18/677 [00:45<29:57,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 19/677 [00:49<34:27,  3.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 20/677 [00:54<38:22,  3.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 21/677 [00:56<35:08,  3.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 22/677 [00:58<32:23,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 23/677 [01:01<29:53,  2.74s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▎         | 24/677 [01:03<28:32,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▎         | 25/677 [01:05<27:31,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 26/677 [01:08<27:30,  2.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 27/677 [01:11<28:04,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 28/677 [01:14<31:51,  2.94s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 29/677 [01:17<32:24,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 30/677 [01:21<33:02,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 31/677 [01:23<31:12,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 32/677 [01:26<30:16,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 33/677 [01:28<29:14,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 34/677 [01:31<28:32,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 35/677 [01:33<28:02,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 36/677 [01:36<27:55,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 37/677 [01:38<27:15,  2.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 38/677 [01:41<26:44,  2.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 39/677 [01:43<26:41,  2.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 40/677 [01:47<29:36,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 41/677 [01:50<30:02,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 42/677 [01:55<37:47,  3.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▋         | 43/677 [02:01<45:51,  4.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▋         | 44/677 [02:05<45:46,  4.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 45/677 [02:08<41:19,  3.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 46/677 [02:11<37:22,  3.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 47/677 [02:14<35:44,  3.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 48/677 [02:18<36:28,  3.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 49/677 [02:21<36:55,  3.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 50/677 [02:24<34:33,  3.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 51/677 [02:27<32:38,  3.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 52/677 [02:30<31:53,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 53/677 [02:33<32:02,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 54/677 [02:36<32:42,  3.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 55/677 [02:42<41:10,  3.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 56/677 [02:45<38:18,  3.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 57/677 [02:51<43:05,  4.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▊         | 58/677 [02:56<46:24,  4.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▊         | 59/677 [02:59<43:31,  4.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 60/677 [03:02<39:56,  3.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 61/677 [03:06<38:07,  3.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 62/677 [03:10<39:04,  3.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 63/677 [03:14<39:05,  3.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 64/677 [03:17<38:05,  3.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 65/677 [03:22<41:30,  4.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 66/677 [03:25<37:48,  3.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 67/677 [03:28<34:48,  3.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 68/677 [03:31<33:12,  3.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 69/677 [03:33<31:23,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 70/677 [03:36<29:48,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 71/677 [03:38<28:33,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 72/677 [03:41<28:16,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 73/677 [03:45<30:46,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 74/677 [03:48<29:38,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 75/677 [03:52<33:21,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 76/677 [03:55<32:05,  3.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█▏        | 77/677 [03:58<31:41,  3.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 78/677 [04:00<30:03,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 79/677 [04:03<28:28,  2.86s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 80/677 [04:06<28:35,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 81/677 [04:09<28:16,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 82/677 [04:11<27:48,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 83/677 [04:14<27:45,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 84/677 [04:17<27:42,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 85/677 [04:20<27:39,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 86/677 [04:24<31:31,  3.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 87/677 [04:27<31:57,  3.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 88/677 [04:30<30:11,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 89/677 [04:33<31:18,  3.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 90/677 [04:36<29:40,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 91/677 [04:39<28:16,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▎        | 92/677 [04:41<27:23,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▎        | 93/677 [04:44<26:35,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 94/677 [04:46<26:07,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 95/677 [04:49<26:10,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 96/677 [04:52<25:51,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 97/677 [04:56<30:32,  3.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 98/677 [04:59<29:15,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 99/677 [05:02<28:48,  2.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 100/677 [05:05<29:23,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 101/677 [05:07<27:52,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 102/677 [05:10<26:42,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 103/677 [05:13<26:24,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 104/677 [05:15<26:20,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 105/677 [05:18<26:21,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 106/677 [05:21<26:25,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 107/677 [05:25<29:32,  3.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 108/677 [05:28<30:57,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 109/677 [05:31<29:31,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 110/677 [05:34<27:51,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▋        | 111/677 [05:36<26:25,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 112/677 [05:39<27:44,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 113/677 [05:43<28:21,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 114/677 [05:46<27:56,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 115/677 [05:48<27:23,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 116/677 [05:51<27:15,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 117/677 [05:54<27:48,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 118/677 [05:59<32:49,  3.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 119/677 [06:02<30:45,  3.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 120/677 [06:05<29:38,  3.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 121/677 [06:08<28:48,  3.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 122/677 [06:11<27:44,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 123/677 [06:13<27:24,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 124/677 [06:17<30:23,  3.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 125/677 [06:20<28:41,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▊        | 126/677 [06:23<27:36,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 127/677 [06:26<27:10,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 128/677 [06:30<29:52,  3.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 129/677 [06:33<28:53,  3.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 130/677 [06:35<27:00,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 131/677 [06:38<26:06,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 132/677 [06:41<25:49,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 133/677 [06:43<25:53,  2.86s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 134/677 [06:46<25:46,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 135/677 [06:50<27:50,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 136/677 [06:53<27:19,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 137/677 [06:56<27:10,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 138/677 [07:01<31:55,  3.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 139/677 [07:04<30:07,  3.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 140/677 [07:06<28:42,  3.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 141/677 [07:09<27:38,  3.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 142/677 [07:12<26:59,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 143/677 [07:15<26:26,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██▏       | 144/677 [07:18<25:57,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██▏       | 145/677 [07:20<25:13,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 146/677 [07:24<26:04,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 147/677 [07:34<45:31,  5.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 148/677 [07:37<40:20,  4.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 149/677 [07:40<35:40,  4.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 150/677 [07:43<32:38,  3.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 151/677 [07:46<30:21,  3.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 152/677 [07:49<29:04,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 153/677 [07:52<27:45,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 154/677 [07:55<28:06,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 155/677 [07:58<26:26,  3.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 156/677 [08:01<28:09,  3.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 157/677 [08:05<29:07,  3.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 158/677 [08:10<32:45,  3.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 159/677 [08:13<31:07,  3.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▎       | 160/677 [08:16<29:17,  3.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 161/677 [08:19<28:37,  3.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 162/677 [08:22<27:56,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 163/677 [08:25<27:33,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 164/677 [08:28<26:50,  3.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 165/677 [08:32<27:46,  3.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 166/677 [08:35<26:46,  3.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 167/677 [08:37<25:32,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 168/677 [08:40<24:23,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 169/677 [08:43<24:16,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 170/677 [08:46<25:37,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 171/677 [08:49<26:11,  3.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 172/677 [08:52<26:06,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 173/677 [08:55<25:53,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 174/677 [08:58<25:33,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 175/677 [09:02<27:37,  3.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 176/677 [09:06<28:47,  3.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 177/677 [09:09<28:11,  3.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▋       | 178/677 [09:12<26:32,  3.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▋       | 179/677 [09:15<26:23,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 180/677 [09:18<25:26,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 181/677 [09:21<24:47,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 182/677 [09:24<24:56,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 183/677 [09:26<23:29,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 184/677 [09:29<22:46,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 185/677 [09:32<22:39,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 186/677 [09:36<25:14,  3.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 187/677 [09:39<24:54,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 188/677 [09:41<24:08,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 189/677 [09:44<23:19,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 190/677 [09:47<22:35,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 191/677 [09:50<23:04,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 192/677 [09:52<22:50,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▊       | 193/677 [09:56<24:21,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▊       | 194/677 [09:59<23:57,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 195/677 [10:01<23:25,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 196/677 [10:04<23:13,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 197/677 [10:08<25:27,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 198/677 [10:11<23:55,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 199/677 [10:14<23:34,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 200/677 [10:16<23:13,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 201/677 [10:19<23:14,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 202/677 [10:22<23:02,  2.91s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 203/677 [10:25<22:55,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 204/677 [10:28<22:27,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 205/677 [10:31<23:10,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 206/677 [10:34<22:43,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 207/677 [10:38<24:45,  3.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 208/677 [10:41<26:08,  3.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 209/677 [10:44<25:21,  3.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 210/677 [10:47<24:47,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 211/677 [10:50<24:27,  3.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███▏      | 212/677 [10:54<24:15,  3.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███▏      | 213/677 [10:56<23:40,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 214/677 [10:59<23:09,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 215/677 [11:02<22:35,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 216/677 [11:05<23:37,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 217/677 [11:09<25:07,  3.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 218/677 [11:12<24:42,  3.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 219/677 [11:15<23:42,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 220/677 [11:18<23:26,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 221/677 [11:23<26:42,  3.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 222/677 [11:27<27:19,  3.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 223/677 [11:30<27:37,  3.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 224/677 [11:33<25:37,  3.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 225/677 [11:36<24:13,  3.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 226/677 [11:40<25:38,  3.41s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▎      | 227/677 [11:43<26:05,  3.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▎      | 228/677 [11:47<25:53,  3.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 229/677 [11:50<24:20,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 230/677 [11:53<24:35,  3.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 231/677 [11:56<24:13,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 232/677 [12:00<24:22,  3.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 233/677 [12:03<24:44,  3.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 234/677 [12:07<25:29,  3.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 235/677 [12:12<28:56,  3.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 236/677 [12:16<30:35,  4.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 237/677 [12:22<33:14,  4.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 238/677 [12:26<31:36,  4.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 239/677 [12:29<29:55,  4.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 240/677 [12:34<30:56,  4.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 241/677 [12:38<29:45,  4.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 242/677 [12:41<29:16,  4.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 243/677 [12:45<27:27,  3.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 244/677 [12:48<26:18,  3.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 245/677 [12:51<25:42,  3.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▋      | 246/677 [12:55<26:10,  3.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▋      | 247/677 [12:58<24:50,  3.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 248/677 [13:01<24:03,  3.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 249/677 [13:04<23:19,  3.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 250/677 [13:07<22:35,  3.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 251/677 [13:11<23:45,  3.35s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 252/677 [13:16<27:17,  3.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 253/677 [13:19<25:45,  3.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 254/677 [13:22<24:30,  3.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 255/677 [13:25<23:26,  3.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 256/677 [13:28<22:42,  3.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 257/677 [13:32<22:20,  3.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 258/677 [13:35<22:03,  3.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 259/677 [13:38<21:34,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 260/677 [13:41<21:20,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▊      | 261/677 [13:44<23:01,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▊      | 262/677 [13:48<23:18,  3.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 263/677 [13:51<22:56,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 264/677 [13:54<21:29,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 265/677 [13:57<20:39,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 266/677 [13:59<20:20,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 267/677 [14:02<20:19,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 268/677 [14:05<19:53,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 269/677 [14:08<19:57,  2.94s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 270/677 [14:11<19:53,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 271/677 [14:14<20:37,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 272/677 [14:18<20:37,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 273/677 [14:20<19:09,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 274/677 [14:22<18:03,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 275/677 [14:25<19:11,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 276/677 [14:28<18:12,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 277/677 [14:30<17:13,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 278/677 [14:32<16:33,  2.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 279/677 [14:35<16:06,  2.43s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████▏     | 280/677 [14:37<15:58,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 281/677 [14:40<16:15,  2.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 282/677 [14:42<16:29,  2.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 283/677 [14:45<16:30,  2.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 284/677 [14:48<17:01,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 285/677 [14:51<17:49,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 286/677 [14:54<19:15,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 287/677 [15:00<24:12,  3.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 288/677 [15:03<23:15,  3.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 289/677 [15:05<21:16,  3.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 290/677 [15:08<20:08,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 291/677 [15:11<19:08,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 292/677 [15:14<18:46,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 293/677 [15:17<19:59,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 294/677 [15:20<19:16,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▎     | 295/677 [15:23<18:25,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▎     | 296/677 [15:25<18:03,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 297/677 [15:28<17:38,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 298/677 [15:31<18:17,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 299/677 [15:34<17:36,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 300/677 [15:36<17:19,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 301/677 [15:39<16:56,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 302/677 [15:41<16:35,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 303/677 [15:44<16:16,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 304/677 [15:47<16:35,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 305/677 [15:50<17:49,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 306/677 [15:53<18:04,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 307/677 [15:56<17:16,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 308/677 [15:58<16:27,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 309/677 [16:01<16:20,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 310/677 [16:04<16:52,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 311/677 [16:06<16:03,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 312/677 [16:08<15:38,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 313/677 [16:11<15:42,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▋     | 314/677 [16:14<15:44,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 315/677 [16:16<15:34,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 316/677 [16:20<16:51,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 317/677 [16:23<18:13,  3.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 318/677 [16:26<17:15,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 319/677 [16:28<16:29,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 320/677 [16:31<15:42,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 321/677 [16:33<16:11,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 322/677 [16:36<15:40,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 323/677 [16:38<15:19,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 324/677 [16:41<15:21,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 325/677 [16:44<15:13,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 326/677 [16:46<15:02,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 327/677 [16:49<15:02,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 328/677 [16:53<17:40,  3.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▊     | 329/677 [16:56<17:51,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▊     | 330/677 [16:59<17:20,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 331/677 [17:02<17:07,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 332/677 [17:04<16:27,  2.86s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 333/677 [17:08<17:11,  3.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 334/677 [17:11<17:26,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 335/677 [17:14<17:27,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 336/677 [17:17<16:51,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 337/677 [17:19<16:20,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 338/677 [17:23<16:48,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 339/677 [17:25<16:11,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 340/677 [17:28<15:18,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 341/677 [17:30<14:34,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 342/677 [17:32<14:25,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 343/677 [17:35<14:46,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 344/677 [17:38<14:26,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 345/677 [17:42<16:29,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 346/677 [17:46<19:38,  3.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████▏    | 347/677 [17:50<20:02,  3.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████▏    | 348/677 [17:54<19:40,  3.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 349/677 [17:57<18:43,  3.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 350/677 [18:00<17:40,  3.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 351/677 [18:02<16:34,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 352/677 [18:06<17:04,  3.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 353/677 [18:08<16:26,  3.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 354/677 [18:12<17:28,  3.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 355/677 [18:15<17:28,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 356/677 [18:19<17:36,  3.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 357/677 [18:21<16:32,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 358/677 [18:25<16:48,  3.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 359/677 [18:28<16:48,  3.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 360/677 [18:30<15:45,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 361/677 [18:33<15:05,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 362/677 [18:36<14:32,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▎    | 363/677 [18:38<14:14,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 364/677 [18:41<14:10,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 365/677 [18:44<13:58,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 366/677 [18:46<13:49,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 367/677 [18:49<14:08,  2.74s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 368/677 [18:52<15:01,  2.92s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 369/677 [18:56<15:33,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 370/677 [18:59<16:14,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 371/677 [19:02<16:03,  3.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 372/677 [19:05<15:18,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 373/677 [19:08<15:23,  3.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 374/677 [19:11<14:36,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 375/677 [19:13<14:21,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 376/677 [19:16<14:26,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 377/677 [19:19<14:06,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 378/677 [19:22<13:54,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 379/677 [19:25<14:46,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 380/677 [19:29<15:32,  3.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▋    | 381/677 [19:31<14:52,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▋    | 382/677 [19:34<14:16,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 383/677 [19:37<13:57,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 384/677 [19:39<13:26,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 385/677 [19:42<13:02,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 386/677 [19:45<13:03,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 387/677 [19:47<12:57,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 388/677 [19:50<12:47,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 389/677 [19:52<12:19,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 390/677 [19:55<12:19,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 391/677 [19:59<13:58,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 392/677 [20:02<14:25,  3.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 393/677 [20:04<13:41,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 394/677 [20:07<13:26,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 395/677 [20:10<12:58,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 396/677 [20:12<12:24,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▊    | 397/677 [20:15<12:17,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 398/677 [20:17<12:10,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 399/677 [20:20<12:12,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 400/677 [20:23<12:07,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 401/677 [20:25<12:06,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 402/677 [20:28<11:47,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 403/677 [20:31<12:41,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 404/677 [20:33<12:07,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 405/677 [20:36<11:40,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 406/677 [20:38<11:46,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 407/677 [20:41<12:31,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 408/677 [20:44<12:00,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 409/677 [20:46<11:42,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 410/677 [20:49<12:08,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 411/677 [20:52<12:11,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 412/677 [20:55<12:11,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 413/677 [20:58<12:01,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 414/677 [21:01<12:51,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████▏   | 415/677 [21:05<13:53,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████▏   | 416/677 [21:07<12:57,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 417/677 [21:10<12:31,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 418/677 [21:13<12:06,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 419/677 [21:15<11:48,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 420/677 [21:18<11:49,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 421/677 [21:21<11:48,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 422/677 [21:24<11:50,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 423/677 [21:26<11:38,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 424/677 [21:29<11:26,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 425/677 [21:32<11:50,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 426/677 [21:36<12:48,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 427/677 [21:38<12:13,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 428/677 [21:41<11:54,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 429/677 [21:44<11:43,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▎   | 430/677 [21:46<11:12,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▎   | 431/677 [21:49<10:54,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 432/677 [21:52<11:27,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 433/677 [21:55<11:21,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 434/677 [21:57<11:13,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 435/677 [22:00<10:59,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 436/677 [22:03<11:36,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 437/677 [22:06<11:53,  2.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 438/677 [22:09<12:00,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 439/677 [22:12<11:13,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 440/677 [22:15<11:17,  2.86s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 441/677 [22:17<11:01,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 442/677 [22:21<11:36,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 443/677 [22:24<11:14,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 444/677 [22:26<10:57,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 445/677 [22:29<10:38,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 446/677 [22:31<10:27,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 447/677 [22:34<10:36,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 448/677 [22:37<10:28,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▋   | 449/677 [22:40<10:09,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▋   | 450/677 [22:42<10:26,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 451/677 [22:45<10:09,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 452/677 [22:48<10:25,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 453/677 [22:51<10:17,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 454/677 [22:54<10:17,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 455/677 [22:57<10:36,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 456/677 [22:59<10:13,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 457/677 [23:02<09:48,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 458/677 [23:05<10:05,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 459/677 [23:09<11:36,  3.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 460/677 [23:11<10:58,  3.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 461/677 [23:15<12:01,  3.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 462/677 [23:19<12:29,  3.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 463/677 [23:22<11:50,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▊   | 464/677 [23:25<11:15,  3.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▊   | 465/677 [23:28<10:51,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 466/677 [23:31<10:19,  2.94s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 467/677 [23:33<09:55,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 468/677 [23:36<10:00,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 469/677 [23:39<09:59,  2.88s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 470/677 [23:42<09:41,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 471/677 [23:44<09:40,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 472/677 [23:48<10:02,  2.94s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 473/677 [23:51<10:32,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 474/677 [23:54<10:11,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 475/677 [23:57<09:46,  2.90s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 476/677 [23:59<09:29,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 477/677 [24:02<09:23,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 478/677 [24:05<08:58,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 479/677 [24:07<09:04,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 480/677 [24:10<09:15,  2.82s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 481/677 [24:13<08:55,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 482/677 [24:16<09:24,  2.89s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████▏  | 483/677 [24:19<09:14,  2.86s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████▏  | 484/677 [24:22<09:13,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 485/677 [24:24<08:47,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 486/677 [24:27<08:22,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 487/677 [24:29<08:09,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 488/677 [24:31<07:49,  2.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 489/677 [24:34<07:46,  2.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 490/677 [24:36<07:37,  2.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 491/677 [24:39<08:03,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 492/677 [24:42<08:26,  2.74s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 493/677 [24:45<08:04,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 494/677 [24:47<07:47,  2.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 495/677 [24:49<07:39,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 496/677 [24:52<08:05,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 497/677 [24:55<07:49,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▎  | 498/677 [24:57<07:32,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▎  | 499/677 [25:00<07:23,  2.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 500/677 [25:02<07:12,  2.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 501/677 [25:04<07:06,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 502/677 [25:07<06:58,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 503/677 [25:09<07:05,  2.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 504/677 [25:13<07:49,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 505/677 [25:15<07:38,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 506/677 [25:18<07:22,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 507/677 [25:20<07:22,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 508/677 [25:23<07:45,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 509/677 [25:26<07:24,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 510/677 [25:28<07:07,  2.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 511/677 [25:31<06:59,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 512/677 [25:33<06:53,  2.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 513/677 [25:35<06:43,  2.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 514/677 [25:38<06:38,  2.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 515/677 [25:40<06:45,  2.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 516/677 [25:44<07:32,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▋  | 517/677 [25:47<07:27,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 518/677 [25:52<09:41,  3.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 519/677 [25:55<09:08,  3.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 520/677 [25:59<09:07,  3.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 521/677 [26:01<08:09,  3.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 522/677 [26:03<07:25,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 523/677 [26:06<06:46,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 524/677 [26:08<06:27,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 525/677 [26:10<06:07,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 526/677 [26:12<05:53,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 527/677 [26:14<05:44,  2.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 528/677 [26:16<05:29,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 529/677 [26:18<05:20,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 530/677 [26:20<05:11,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 531/677 [26:23<05:27,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▊  | 532/677 [26:25<05:11,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▊  | 533/677 [26:27<05:09,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 534/677 [26:29<05:02,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 535/677 [26:31<04:53,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 536/677 [26:33<04:50,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 537/677 [26:35<04:48,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 538/677 [26:37<04:43,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 539/677 [26:39<04:41,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 540/677 [26:41<04:35,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 541/677 [26:43<04:36,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 542/677 [26:45<04:31,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 543/677 [26:48<04:52,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 544/677 [26:50<04:46,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 545/677 [26:52<04:44,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 546/677 [26:54<04:40,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 547/677 [26:56<04:38,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 548/677 [27:02<06:37,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 549/677 [27:05<06:46,  3.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 550/677 [27:09<07:09,  3.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████▏ | 551/677 [27:11<06:17,  2.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 552/677 [27:13<05:39,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 553/677 [27:15<05:12,  2.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 554/677 [27:17<04:52,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 555/677 [27:20<04:55,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 556/677 [27:22<04:36,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 557/677 [27:23<04:20,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 558/677 [27:25<04:06,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 559/677 [27:27<03:59,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 560/677 [27:29<03:53,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 561/677 [27:31<03:49,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 562/677 [27:33<03:45,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 563/677 [27:35<03:47,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 564/677 [27:37<03:40,  1.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 565/677 [27:39<03:39,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▎ | 566/677 [27:41<03:52,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 567/677 [27:43<03:46,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 568/677 [27:45<03:39,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 569/677 [27:47<03:31,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 570/677 [27:49<03:30,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 571/677 [27:51<03:32,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 572/677 [27:53<03:31,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 573/677 [27:55<03:32,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 574/677 [27:57<03:27,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 575/677 [27:59<03:23,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 576/677 [28:01<03:29,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 577/677 [28:04<03:29,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 578/677 [28:06<03:48,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 579/677 [28:09<03:50,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 580/677 [28:11<03:52,  2.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 581/677 [28:14<03:54,  2.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 582/677 [28:17<04:00,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 583/677 [28:19<03:43,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▋ | 584/677 [28:21<03:32,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▋ | 585/677 [28:23<03:24,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 586/677 [28:25<03:28,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 587/677 [28:28<03:30,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 588/677 [28:30<03:32,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 589/677 [28:33<03:33,  2.43s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 590/677 [28:35<03:21,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 591/677 [28:37<03:10,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 592/677 [28:39<03:01,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 593/677 [28:41<02:54,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 594/677 [28:43<02:49,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 595/677 [28:45<02:48,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 596/677 [28:47<02:47,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 597/677 [28:49<02:44,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 598/677 [28:51<02:40,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 599/677 [28:53<02:37,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▊ | 600/677 [28:55<02:34,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 601/677 [28:57<02:43,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 602/677 [28:59<02:37,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 603/677 [29:02<02:42,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 604/677 [29:04<02:36,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 605/677 [29:06<02:31,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 606/677 [29:08<02:37,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 607/677 [29:10<02:32,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 608/677 [29:12<02:27,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 609/677 [29:14<02:22,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 610/677 [29:16<02:17,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 611/677 [29:18<02:12,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 612/677 [29:21<02:19,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 613/677 [29:22<02:12,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 614/677 [29:25<02:10,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 615/677 [29:27<02:06,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 616/677 [29:29<02:03,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 617/677 [29:30<01:59,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████▏| 618/677 [29:32<01:56,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████▏| 619/677 [29:34<01:55,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 620/677 [29:37<01:56,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 621/677 [29:39<01:56,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 622/677 [29:41<01:53,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 623/677 [29:43<01:51,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 624/677 [29:45<01:56,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 625/677 [29:47<01:49,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 626/677 [29:49<01:46,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 627/677 [29:51<01:43,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 628/677 [29:53<01:42,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 629/677 [29:55<01:40,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 630/677 [29:57<01:36,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 631/677 [29:59<01:33,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 632/677 [30:02<01:32,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▎| 633/677 [30:04<01:30,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▎| 634/677 [30:06<01:27,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 635/677 [30:08<01:26,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 636/677 [30:10<01:29,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 637/677 [30:12<01:24,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 638/677 [30:14<01:19,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 639/677 [30:16<01:16,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 640/677 [30:18<01:13,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 641/677 [30:20<01:10,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 642/677 [30:22<01:07,  1.94s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 643/677 [30:24<01:06,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 644/677 [30:26<01:04,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 645/677 [30:28<01:04,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 646/677 [30:30<01:03,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 647/677 [30:32<01:01,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 648/677 [30:34<01:02,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 649/677 [30:36<00:59,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 650/677 [30:38<00:55,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 651/677 [30:40<00:52,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▋| 652/677 [30:42<00:50,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▋| 653/677 [30:44<00:48,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 654/677 [30:46<00:46,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 655/677 [30:48<00:44,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 656/677 [30:50<00:41,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 657/677 [30:52<00:41,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 658/677 [30:55<00:39,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 659/677 [30:57<00:39,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 660/677 [30:59<00:38,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 661/677 [31:02<00:37,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 662/677 [31:04<00:33,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 663/677 [31:06<00:29,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 664/677 [31:08<00:27,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 665/677 [31:10<00:25,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 666/677 [31:12<00:23,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▊| 667/677 [31:14<00:21,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▊| 668/677 [31:16<00:18,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 669/677 [31:18<00:16,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 670/677 [31:20<00:14,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 671/677 [31:23<00:13,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 672/677 [31:25<00:10,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 673/677 [31:27<00:08,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 674/677 [31:29<00:06,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 675/677 [31:31<00:04,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 676/677 [31:34<00:02,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|██████████| 677/677 [31:36<00:00,  2.80s/it]

done!

musicnn:val:   0%|          | 0/141 [00:00<?, ?it/s]

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   1%|          | 1/141 [00:02<04:47,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   1%|▏         | 2/141 [00:04<04:51,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   2%|▏         | 3/141 [00:07<05:38,  2.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   3%|▎         | 4/141 [00:09<05:25,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   4%|▎         | 5/141 [00:12<06:01,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   4%|▍         | 6/141 [00:14<05:42,  2.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   5%|▍         | 7/141 [00:17<05:46,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   6%|▌         | 8/141 [00:20<05:44,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   6%|▋         | 9/141 [00:22<05:34,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   7%|▋         | 10/141 [00:25<05:34,  2.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   8%|▊         | 11/141 [00:27<05:21,  2.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   9%|▊         | 12/141 [00:29<05:04,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   9%|▉         | 13/141 [00:31<04:55,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  10%|▉         | 14/141 [00:33<04:43,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  11%|█         | 15/141 [00:35<04:36,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  11%|█▏        | 16/141 [00:37<04:31,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  12%|█▏        | 17/141 [00:40<04:46,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  13%|█▎        | 18/141 [00:42<04:33,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  13%|█▎        | 19/141 [00:44<04:24,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  14%|█▍        | 20/141 [00:46<04:13,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  15%|█▍        | 21/141 [00:48<04:09,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  16%|█▌        | 22/141 [00:50<04:07,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  16%|█▋        | 23/141 [00:52<03:59,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  17%|█▋        | 24/141 [00:54<04:01,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  18%|█▊        | 25/141 [00:56<04:06,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  18%|█▊        | 26/141 [00:58<03:58,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  19%|█▉        | 27/141 [01:01<04:16,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  20%|█▉        | 28/141 [01:04<04:45,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  21%|██        | 29/141 [01:08<05:13,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  21%|██▏       | 30/141 [01:10<04:58,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  22%|██▏       | 31/141 [01:13<05:06,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  23%|██▎       | 32/141 [01:16<05:08,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  23%|██▎       | 33/141 [01:19<04:57,  2.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  24%|██▍       | 34/141 [01:21<04:43,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  25%|██▍       | 35/141 [01:24<04:38,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  26%|██▌       | 36/141 [01:26<04:30,  2.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  26%|██▌       | 37/141 [01:29<04:30,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  27%|██▋       | 38/141 [01:31<04:24,  2.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  28%|██▊       | 39/141 [01:34<04:37,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  28%|██▊       | 40/141 [01:38<05:00,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  29%|██▉       | 41/141 [01:41<05:09,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  30%|██▉       | 42/141 [01:44<04:52,  2.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  30%|███       | 43/141 [01:47<04:38,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  31%|███       | 44/141 [01:49<04:32,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  32%|███▏      | 45/141 [01:52<04:22,  2.74s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  33%|███▎      | 46/141 [01:55<04:19,  2.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  33%|███▎      | 47/141 [01:57<04:10,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  34%|███▍      | 48/141 [02:00<04:05,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  35%|███▍      | 49/141 [02:02<04:03,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  35%|███▌      | 50/141 [02:05<04:12,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  36%|███▌      | 51/141 [02:08<04:04,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  37%|███▋      | 52/141 [02:11<04:12,  2.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  38%|███▊      | 53/141 [02:14<04:04,  2.78s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  38%|███▊      | 54/141 [02:16<03:55,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  39%|███▉      | 55/141 [02:19<03:50,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  40%|███▉      | 56/141 [02:21<03:39,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  40%|████      | 57/141 [02:24<03:40,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  41%|████      | 58/141 [02:27<03:37,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  42%|████▏     | 59/141 [02:29<03:35,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  43%|████▎     | 60/141 [02:32<03:29,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  43%|████▎     | 61/141 [02:34<03:27,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  44%|████▍     | 62/141 [02:37<03:33,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  45%|████▍     | 63/141 [02:40<03:41,  2.85s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  45%|████▌     | 64/141 [02:44<03:47,  2.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  46%|████▌     | 65/141 [02:47<03:42,  2.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  47%|████▋     | 66/141 [02:50<03:44,  2.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  48%|████▊     | 67/141 [02:52<03:35,  2.91s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  48%|████▊     | 68/141 [02:55<03:23,  2.79s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  49%|████▉     | 69/141 [02:57<03:15,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  50%|████▉     | 70/141 [03:00<03:07,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  50%|█████     | 71/141 [03:02<02:58,  2.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  51%|█████     | 72/141 [03:05<02:52,  2.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  52%|█████▏    | 73/141 [03:08<03:05,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  52%|█████▏    | 74/141 [03:11<03:01,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  53%|█████▎    | 75/141 [03:13<02:58,  2.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  54%|█████▍    | 76/141 [03:16<02:59,  2.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  55%|█████▍    | 77/141 [03:19<02:50,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  55%|█████▌    | 78/141 [03:21<02:42,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  56%|█████▌    | 79/141 [03:23<02:38,  2.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  57%|█████▋    | 80/141 [03:26<02:34,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  57%|█████▋    | 81/141 [03:28<02:30,  2.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  58%|█████▊    | 82/141 [03:31<02:29,  2.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  59%|█████▉    | 83/141 [03:34<02:29,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  60%|█████▉    | 84/141 [03:36<02:27,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  60%|██████    | 85/141 [03:39<02:30,  2.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  61%|██████    | 86/141 [03:42<02:29,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  62%|██████▏   | 87/141 [03:45<02:31,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  62%|██████▏   | 88/141 [03:48<02:24,  2.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  63%|██████▎   | 89/141 [03:50<02:19,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  64%|██████▍   | 90/141 [03:53<02:16,  2.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  65%|██████▍   | 91/141 [03:55<02:12,  2.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  65%|██████▌   | 92/141 [03:58<02:07,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  66%|██████▌   | 93/141 [04:01<02:06,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  67%|██████▋   | 94/141 [04:03<02:00,  2.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  67%|██████▋   | 95/141 [04:05<01:57,  2.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  68%|██████▊   | 96/141 [04:13<03:00,  4.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  69%|██████▉   | 97/141 [04:16<02:47,  3.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  70%|██████▉   | 98/141 [04:20<02:38,  3.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  70%|███████   | 99/141 [04:24<02:41,  3.84s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  71%|███████   | 100/141 [04:27<02:27,  3.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  72%|███████▏  | 101/141 [04:30<02:17,  3.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  72%|███████▏  | 102/141 [04:33<02:09,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  73%|███████▎  | 103/141 [04:36<02:03,  3.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  74%|███████▍  | 104/141 [04:39<01:59,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  74%|███████▍  | 105/141 [04:43<02:06,  3.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  75%|███████▌  | 106/141 [04:47<01:59,  3.41s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  76%|███████▌  | 107/141 [04:50<01:52,  3.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  77%|███████▋  | 108/141 [04:53<01:45,  3.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  77%|███████▋  | 109/141 [04:55<01:38,  3.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  78%|███████▊  | 110/141 [04:59<01:40,  3.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  79%|███████▊  | 111/141 [05:02<01:33,  3.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  79%|███████▉  | 112/141 [05:05<01:29,  3.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  80%|████████  | 113/141 [05:08<01:26,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  81%|████████  | 114/141 [05:11<01:27,  3.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  82%|████████▏ | 115/141 [05:16<01:34,  3.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  82%|████████▏ | 116/141 [05:19<01:26,  3.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  83%|████████▎ | 117/141 [05:22<01:19,  3.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  84%|████████▎ | 118/141 [05:25<01:13,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  84%|████████▍ | 119/141 [05:28<01:08,  3.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  85%|████████▌ | 120/141 [05:31<01:02,  2.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  86%|████████▌ | 121/141 [05:34<01:00,  3.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  87%|████████▋ | 122/141 [05:37<01:01,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  87%|████████▋ | 123/141 [05:40<00:56,  3.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  88%|████████▊ | 124/141 [05:45<01:01,  3.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  89%|████████▊ | 125/141 [05:49<00:58,  3.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  89%|████████▉ | 126/141 [05:52<00:52,  3.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  90%|█████████ | 127/141 [05:55<00:45,  3.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  91%|█████████ | 128/141 [05:57<00:39,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  91%|█████████▏| 129/141 [05:59<00:33,  2.83s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  92%|█████████▏| 130/141 [06:02<00:30,  2.77s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  93%|█████████▎| 131/141 [06:05<00:26,  2.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  94%|█████████▎| 132/141 [06:07<00:23,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  94%|█████████▍| 133/141 [06:10<00:20,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  95%|█████████▌| 134/141 [06:13<00:20,  2.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  96%|█████████▌| 135/141 [06:18<00:20,  3.41s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  96%|█████████▋| 136/141 [06:21<00:16,  3.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  97%|█████████▋| 137/141 [06:24<00:12,  3.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  98%|█████████▊| 138/141 [06:27<00:09,  3.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  99%|█████████▊| 139/141 [06:29<00:05,  2.91s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  99%|█████████▉| 140/141 [06:32<00:02,  2.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val: 100%|██████████| 141/141 [06:35<00:00,  2.81s/it]

done!

musicnn:test:   0%|          | 0/153 [00:00<?, ?it/s]

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   1%|          | 1/153 [00:02<05:12,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   1%|▏         | 2/153 [00:04<05:10,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   2%|▏         | 3/153 [00:06<05:46,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   3%|▎         | 4/153 [00:09<06:16,  2.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   3%|▎         | 5/153 [00:13<07:34,  3.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   4%|▍         | 6/153 [00:17<08:35,  3.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   5%|▍         | 7/153 [00:21<08:32,  3.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   5%|▌         | 8/153 [00:24<08:03,  3.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   6%|▌         | 9/153 [00:26<07:20,  3.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   7%|▋         | 10/153 [00:29<06:41,  2.81s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   7%|▋         | 11/153 [00:31<06:12,  2.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   8%|▊         | 12/153 [00:33<05:50,  2.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   8%|▊         | 13/153 [00:35<05:39,  2.43s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   9%|▉         | 14/153 [00:38<05:31,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  10%|▉         | 15/153 [00:40<05:20,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  10%|█         | 16/153 [00:43<05:38,  2.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  11%|█         | 17/153 [00:45<05:25,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  12%|█▏        | 18/153 [00:47<05:16,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  12%|█▏        | 19/153 [00:49<05:18,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  13%|█▎        | 20/153 [00:52<05:13,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  14%|█▎        | 21/153 [00:54<05:06,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  14%|█▍        | 22/153 [00:56<05:04,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  15%|█▌        | 23/153 [00:58<04:53,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  16%|█▌        | 24/153 [01:01<04:48,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  16%|█▋        | 25/153 [01:03<04:45,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  17%|█▋        | 26/153 [01:05<04:41,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  18%|█▊        | 27/153 [01:08<05:04,  2.41s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  18%|█▊        | 28/153 [01:10<04:58,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  19%|█▉        | 29/153 [01:12<04:47,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  20%|█▉        | 30/153 [01:15<04:39,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  20%|██        | 31/153 [01:17<04:35,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  21%|██        | 32/153 [01:19<04:30,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  22%|██▏       | 33/153 [01:21<04:24,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  22%|██▏       | 34/153 [01:23<04:20,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  23%|██▎       | 35/153 [01:26<04:19,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  24%|██▎       | 36/153 [01:28<04:18,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  24%|██▍       | 37/153 [01:30<04:14,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  25%|██▍       | 38/153 [01:32<04:12,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  25%|██▌       | 39/153 [01:35<04:33,  2.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  26%|██▌       | 40/153 [01:37<04:23,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  27%|██▋       | 41/153 [01:39<04:15,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  27%|██▋       | 42/153 [01:42<04:11,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  28%|██▊       | 43/153 [01:44<04:10,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  29%|██▉       | 44/153 [01:46<04:03,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  29%|██▉       | 45/153 [01:48<04:01,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  30%|███       | 46/153 [01:50<03:57,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  31%|███       | 47/153 [01:52<03:50,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  31%|███▏      | 48/153 [01:55<03:51,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  32%|███▏      | 49/153 [01:57<03:47,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  33%|███▎      | 50/153 [01:59<03:43,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  33%|███▎      | 51/153 [02:02<04:01,  2.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  34%|███▍      | 52/153 [02:04<03:53,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  35%|███▍      | 53/153 [02:06<03:46,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  35%|███▌      | 54/153 [02:08<03:43,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  36%|███▌      | 55/153 [02:11<03:40,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  37%|███▋      | 56/153 [02:13<03:36,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  37%|███▋      | 57/153 [02:15<03:32,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  38%|███▊      | 58/153 [02:17<03:27,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  39%|███▊      | 59/153 [02:19<03:27,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  39%|███▉      | 60/153 [02:22<03:23,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  40%|███▉      | 61/153 [02:24<03:19,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  41%|████      | 62/153 [02:26<03:16,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  41%|████      | 63/153 [02:29<03:35,  2.39s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  42%|████▏     | 64/153 [02:31<03:26,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  42%|████▏     | 65/153 [02:33<03:21,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  43%|████▎     | 66/153 [02:35<03:18,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  44%|████▍     | 67/153 [02:38<03:14,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  44%|████▍     | 68/153 [02:40<03:10,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  45%|████▌     | 69/153 [02:42<03:06,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  46%|████▌     | 70/153 [02:44<03:03,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  46%|████▋     | 71/153 [02:46<03:02,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  47%|████▋     | 72/153 [02:49<02:59,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  48%|████▊     | 73/153 [02:51<02:56,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  48%|████▊     | 74/153 [02:54<03:08,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  49%|████▉     | 75/153 [02:56<03:04,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  50%|████▉     | 76/153 [02:58<03:01,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  50%|█████     | 77/153 [03:00<02:53,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  51%|█████     | 78/153 [03:03<02:50,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  52%|█████▏    | 79/153 [03:05<02:45,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  52%|█████▏    | 80/153 [03:07<02:43,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  53%|█████▎    | 81/153 [03:09<02:41,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  54%|█████▎    | 82/153 [03:11<02:37,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  54%|█████▍    | 83/153 [03:14<02:34,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  55%|█████▍    | 84/153 [03:16<02:32,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  56%|█████▌    | 85/153 [03:18<02:28,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  56%|█████▌    | 86/153 [03:21<02:38,  2.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  57%|█████▋    | 87/153 [03:23<02:32,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  58%|█████▊    | 88/153 [03:25<02:27,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  58%|█████▊    | 89/153 [03:27<02:25,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  59%|█████▉    | 90/153 [03:30<02:21,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  59%|█████▉    | 91/153 [03:32<02:16,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  60%|██████    | 92/153 [03:34<02:14,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  61%|██████    | 93/153 [03:36<02:11,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  61%|██████▏   | 94/153 [03:38<02:08,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  62%|██████▏   | 95/153 [03:40<02:06,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  63%|██████▎   | 96/153 [03:43<02:05,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  63%|██████▎   | 97/153 [03:46<02:19,  2.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  64%|██████▍   | 98/153 [03:48<02:13,  2.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  65%|██████▍   | 99/153 [03:50<02:09,  2.40s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  65%|██████▌   | 100/153 [03:53<02:03,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  66%|██████▌   | 101/153 [03:55<02:00,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  67%|██████▋   | 102/153 [03:57<01:58,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  67%|██████▋   | 103/153 [03:59<01:53,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  68%|██████▊   | 104/153 [04:02<01:50,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  69%|██████▊   | 105/153 [04:04<01:46,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  69%|██████▉   | 106/153 [04:06<01:43,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  70%|██████▉   | 107/153 [04:08<01:40,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  71%|███████   | 108/153 [04:10<01:40,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  71%|███████   | 109/153 [04:15<02:08,  2.91s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  72%|███████▏  | 110/153 [04:17<02:00,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  73%|███████▎  | 111/153 [04:20<01:50,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  73%|███████▎  | 112/153 [04:22<01:42,  2.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  74%|███████▍  | 113/153 [04:25<01:49,  2.74s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  75%|███████▍  | 114/153 [04:27<01:41,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  75%|███████▌  | 115/153 [04:29<01:31,  2.41s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  76%|███████▌  | 116/153 [04:31<01:23,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  76%|███████▋  | 117/153 [04:33<01:18,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  77%|███████▋  | 118/153 [04:35<01:13,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  78%|███████▊  | 119/153 [04:37<01:10,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  78%|███████▊  | 120/153 [04:39<01:07,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  79%|███████▉  | 121/153 [04:42<01:10,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  80%|███████▉  | 122/153 [04:44<01:06,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  80%|████████  | 123/153 [04:46<01:02,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  81%|████████  | 124/153 [04:48<00:59,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  82%|████████▏ | 125/153 [04:50<00:56,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  82%|████████▏ | 126/153 [04:52<00:54,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  83%|████████▎ | 127/153 [04:54<00:52,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  84%|████████▎ | 128/153 [04:56<00:51,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  84%|████████▍ | 129/153 [04:58<00:49,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  85%|████████▍ | 130/153 [05:00<00:47,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  86%|████████▌ | 131/153 [05:02<00:44,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  86%|████████▋ | 132/153 [05:04<00:45,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  87%|████████▋ | 133/153 [05:07<00:44,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  88%|████████▊ | 134/153 [05:09<00:44,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  88%|████████▊ | 135/153 [05:12<00:46,  2.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  89%|████████▉ | 136/153 [05:15<00:44,  2.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  90%|████████▉ | 137/153 [05:18<00:41,  2.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  90%|█████████ | 138/153 [05:21<00:39,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  91%|█████████ | 139/153 [05:23<00:35,  2.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  92%|█████████▏| 140/153 [05:25<00:31,  2.43s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  92%|█████████▏| 141/153 [05:27<00:28,  2.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  93%|█████████▎| 142/153 [05:29<00:25,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  93%|█████████▎| 143/153 [05:31<00:22,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  94%|█████████▍| 144/153 [05:34<00:20,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  95%|█████████▍| 145/153 [05:36<00:17,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  95%|█████████▌| 146/153 [05:38<00:15,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  96%|█████████▌| 147/153 [05:40<00:12,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  97%|█████████▋| 148/153 [05:42<00:10,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  97%|█████████▋| 149/153 [05:44<00:08,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  98%|█████████▊| 150/153 [05:46<00:06,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  99%|█████████▊| 151/153 [05:48<00:04,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  99%|█████████▉| 152/153 [05:50<00:02,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test: 100%|██████████| 153/153 [05:52<00:00,  2.30s/it]

done!

,model,split,n_clips,embedding_dim,total_seconds,seconds_per_clip,n_failures
0,musicnn,train,677,753,1896.147807,2.800809,0
1,musicnn,val,141,753,395.918890,2.807935,0
2,musicnn,test,153,753,352.420708,2.303403,0

## 4. MERT embedding extraction

MERT expects **24 kHz mono audio**, so clips are resampled from GTZAN's native
22.05 kHz. We mean-pool across the time dimension of the last hidden state to get
a clip-level vector. `MERT-v1-330M` outputs 1024-dim embeddings; the smaller
`MERT-v1-95M` outputs 768-dim — swap the `MODEL_NAME` if you're CPU-bound.

In [ ]:
MODEL_NAME = "m-a-p/MERT-v1-95M"   # swap to "m-a-p/MERT-v1-330M" if have GPU for faster extraction
TARGET_SR = 24000

mert_processor = Wav2Vec2FeatureExtractor.from_pretrained(MODEL_NAME, trust_remote_code=True)
mert_model = AutoModel.from_pretrained(MODEL_NAME, trust_remote_code=True).to(DEVICE)
mert_model.eval()


def extract_mert_embedding(file_path):
    """Return a single fixed-length embedding vector for one audio clip."""
    waveform, sr = librosa.load(file_path, sr=TARGET_SR, mono=True)

    inputs = mert_processor(
        waveform, sampling_rate=TARGET_SR, return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = mert_model(**inputs, output_hidden_states=True)

    # Mean-pool the final hidden state over the time dimension
    last_hidden = outputs.hidden_states[-1].squeeze(0)   # (time, hidden_dim)
    embedding = last_hidden.mean(dim=0).cpu().numpy()
    return embedding


def extract_mert_split(df, split_name, out_dir="embeddings"):
    os.makedirs(out_dir, exist_ok=True)
    split_df = df[df["split"] == split_name].reset_index(drop=True)

    embeddings = []
    labels = []
    failures = []
    start = time.time()

    for _, row in tqdm(split_df.iterrows(), total=len(split_df), desc=f"MERT:{split_name}"):
        try:
            emb = extract_mert_embedding(row["file_path"])
            embeddings.append(emb)
            labels.append(row["genre"])
        except Exception as e:
            failures.append((row["file_path"], str(e)))

    elapsed = time.time() - start
    embeddings = np.stack(embeddings)

    np.save(f"{out_dir}/mert_{split_name}.npy", embeddings)
    pd.DataFrame({"genre": labels}).to_csv(
        f"{out_dir}/mert_{split_name}_labels.csv", index=False
    )

    if failures:
        print(f"  {len(failures)} clips failed extraction — see failures list")

    return {
        "model": "mert",
        "split": split_name,
        "n_clips": len(embeddings),
        "embedding_dim": embeddings.shape[1],
        "total_seconds": elapsed,
        "seconds_per_clip": elapsed / max(len(embeddings), 1),
        "n_failures": len(failures),
    }


mert_timing = []
for split in ["train", "val", "test"]:
    mert_timing.append(extract_mert_split(tracks_df, split))

pd.DataFrame(mert_timing)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

WARNING: feature_extractor_cqt requires the libray 'nnAudio'

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 12965.68it/s]
MERT:train:   0%|          | 0/677 [00:00<?, ?it/s][transformers] `use_return_dict` is deprecated! Use `return_dict` instead!
MERT:train: 100%|██████████| 677/677 [1:30:47<00:00,  8.05s/it]
MERT:val: 100%|██████████| 141/141 [17:28<00:00,  7.44s/it]
MERT:test: 100%|██████████| 153/153 [19:16<00:00,  7.56s/it]

,model,split,n_clips,embedding_dim,total_seconds,seconds_per_clip,n_failures
0,mert,train,677,768,5447.580055,8.046647,0
1,mert,val,141,768,1048.624017,7.437050,0
2,mert,test,153,768,1156.475637,7.558664,0

## 5. Consolidate timing + sanity checks

Save extraction timing for both models — this feeds the cost/latency comparison
table in the Sprint 4 writeup (accuracy isn't the only axis your capstone should
compare on).

In [ ]:
timing_df = pd.DataFrame(musicnn_timing + mert_timing)
os.makedirs("embeddings", exist_ok=True)
timing_df.to_csv("embeddings/extraction_timing.csv", index=False)
timing_df

# Quick sanity check: confirm labels line up across splits/models before moving on
for model in ["musicnn", "mert"]:
    for split in ["train", "val", "test"]:
        emb = np.load(f"embeddings/{model}_{split}.npy")
        lbl = pd.read_csv(f"embeddings/{model}_{split}_labels.csv")
        assert emb.shape[0] == len(lbl), f"Mismatch: {model}/{split}"
        print(f"{model:8s} {split:5s} -> embeddings {emb.shape}, labels {len(lbl)}")

musicnn  train -> embeddings (677, 753), labels 677
musicnn  val   -> embeddings (141, 753), labels 141
musicnn  test  -> embeddings (153, 753), labels 153
mert     train -> embeddings (677, 768), labels 677
mert     val   -> embeddings (141, 768), labels 141
mert     test  -> embeddings (153, 768), labels 153

---
**Next step:** open `Sprint4_Comparison_Workflow.md` to train classifier heads on
these embeddings, evaluate against your Sprint 3 CNN test metrics, and build the
final 3-way comparison table.