# Rhythmx — Sprint 4: Pretrained Embedding Extraction
### CNN (baseline, from Sprint 3) vs. musicnn vs. MERT

This notebook extracts embeddings from two pretrained audio models — **musicnn**
(music-specific auto-tagging CNN) and **MERT** (self-supervised music foundation model)
— for the same GTZAN clips used to train `GenreCNN`. These embeddings feed lightweight
classifier heads in the companion workflow doc (`Sprint4_Comparison_Workflow.md`),
so we can benchmark our from-scratch CNN against transfer-learning baselines on
identical train/val/test splits.

**Outputs of this notebook:**
- `embeddings/musicnn_{split}.npy` + `embeddings/musicnn_{split}_labels.csv`
- `embeddings/mert_{split}.npy` + `embeddings/mert_{split}_labels.csv`
- `embeddings/extraction_timing.csv` (for the cost-comparison table in Sprint 4)

**Prerequisite:** run this against the exact same file list / split as `CNN_Training.ipynb`
so results are directly comparable. Do not re-split randomly here.

## 1. Environment setup

musicnn is TensorFlow-based; MERT is PyTorch/HuggingFace-based. Rather than fight
dependency conflicts inside your existing `DS_class` conda env (which is tuned for
your PyTorch CNN pipeline), create an isolated env just for embedding extraction.
Run this in your WSL2 Ubuntu terminal:

```bash
conda create -n rhythmx_embed python=3.10 -y
conda activate rhythmx_embed

# musicnn dependency pin (numpy<1.17,>=1.14.5); those numpy versions are incompatible with Python 3.10
# Python 3.10 and other newer packages don't have the distutils/ccompiler.py those older numpy versions depend on
# musicnn (TF-based auto-tagger)
pip install musicnn --no-deps
pip install "numpy>=1.19,<1.24" "tensorflow==3.15.0.post1"

# MERT (HuggingFace)
pip install transformers torch torchaudio accelerate soxr

# shared utilities
pip install "librosa>=0.7.0,<0.9" soundfile audioread pandas numpy scikit-learn psycopg2-binary tqdm "setuptools<81"

# register the env as a Jupyter kernel
pip install ipykernel
python -m ipykernel install --user --name rhythmx_embed --display-name "Python (rhythmx_embed)"
```

Then select the **Python (rhythmx_embed)** kernel for this notebook in VS Code
before running the cells below.

> Note: MERT-v1-330M is ~330M params and will be slow on CPU. If you don't have GPU
> access in WSL2 (check with `nvidia-smi`), switch to `m-a-p/MERT-v1-95M` below —
> it's noted inline as a swap-in.

In [1]:
import os
import time
import json
import numpy as np
import pandas as pd
import librosa
import torch
from tqdm import tqdm

# musicnn
from musicnn.extractor import extractor as musicnn_extractor

# MERT
from transformers import Wav2Vec2FeatureExtractor, AutoModel
print("transformers audio imports OK")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/librosa/util/files.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-07-11 19:31:57.164083: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-11 19:31:57.328776: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-07-11 19:31:57.571712: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-07-11 19:31:57.571767: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-07-11 19:31:57.584538: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-07-11 19:31:57.640143: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-07-11 19:31:57.641039: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-11 19:31:59.467020: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

transformers audio imports OK
Using device: cpu

## 2. Load the exact same train/val/test split used for `GenreCNN`

Point this at whatever your CNN notebook used as the source of truth — either the
`vw_clean_tracks` Postgres view (if the split/fold was persisted there) or a saved
CSV of file paths + labels + split assignment. **Do not regenerate the split here.**

Adjust the query/path below to match your actual Sprint 3 setup.

In [2]:
# Pull from Postgres (music_genre_db) ---
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    dbname="music_genre_db",
    user="postgres",          # adjust to your WSL2 Postgres user
    password=os.environ.get("PGPASSWORD", ""),
    port=5432,
)

query = """
    SELECT track_id, file_path, label AS genre, split
    FROM vw_clean_tracks
    WHERE split IN ('train', 'val', 'test')
    ORDER BY track_id
"""
tracks_df = pd.read_sql(query, conn)
conn.close()

tracks_df.head()

split_counts = tracks_df["split"].value_counts()
print(split_counts)

# Sanity check against Sprint 3's known split sizes
expected_counts = {"train": 677, "val": 141, "test": 153}
for split_name, expected_n in expected_counts.items():
    actual_n = split_counts.get(split_name, 0)
    assert actual_n == expected_n, (
        f"Split mismatch for '{split_name}': expected {expected_n}, got {actual_n}. "
        "vw_clean_tracks may have changed since Sprint 3 — investigate before extracting embeddings."
    )

print("Split counts match Sprint 3 exactly — safe to proceed.")
tracks_df.head()

split
train    677
test     153
val      141
Name: count, dtype: int64
Split counts match Sprint 3 exactly — safe to proceed.

/tmp/ipykernel_39220/1076542290.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tracks_df = pd.read_sql(query, conn)

   track_id                                      file_path  genre  split
0         1  ../Data_Music/processed/blues/blues.00000.wav  blues    val
1         2  ../Data_Music/processed/blues/blues.00001.wav  blues  train
2         3  ../Data_Music/processed/blues/blues.00002.wav  blues  train
3         4  ../Data_Music/processed/blues/blues.00003.wav  blues   test
4         5  ../Data_Music/processed/blues/blues.00004.wav  blues   test

## 3. musicnn embedding extraction

`musicnn.extractor` returns penultimate-layer features per clip (taggram + pooled
embedding). We use the pooled `features['mean_pool']` (or `features['max_pool']`)
representation as our fixed-length embedding — 200-dim for the `MSD_musicnn` model,
753-dim for the `MTT_musicnn` model. `MSD_musicnn` (trained on the Million Song
Dataset) is the closer match to a genre-classification task; start there.

In [3]:
def extract_musicnn_embedding(file_path, model="MSD_musicnn"):
    """Return a single fixed-length embedding vector for one audio clip."""
    taggram, tags, features = musicnn_extractor(
        file_path, model=model, extract_features=True
    )
    # mean_pool: (n_frames, 200) -> average over time for a clip-level vector
    embedding = features["mean_pool"].mean(axis=0)
    return embedding


def extract_musicnn_split(df, split_name, out_dir="embeddings"):
    os.makedirs(out_dir, exist_ok=True)
    split_df = df[df["split"] == split_name].reset_index(drop=True)

    embeddings = []
    labels = []
    failures = []
    start = time.time()

    for _, row in tqdm(split_df.iterrows(), total=len(split_df), desc=f"musicnn:{split_name}"):
        try:
            emb = extract_musicnn_embedding(row["file_path"])
            embeddings.append(emb)
            labels.append(row["genre"])
        except Exception as e:
            failures.append((row["file_path"], str(e)))

    elapsed = time.time() - start
    embeddings = np.stack(embeddings)

    np.save(f"{out_dir}/musicnn_{split_name}.npy", embeddings)
    pd.DataFrame({"genre": labels}).to_csv(
        f"{out_dir}/musicnn_{split_name}_labels.csv", index=False
    )

    if failures:
        print(f"  {len(failures)} clips failed extraction — see failures list")

    return {
        "model": "musicnn",
        "split": split_name,
        "n_clips": len(embeddings),
        "embedding_dim": embeddings.shape[1],
        "total_seconds": elapsed,
        "seconds_per_clip": elapsed / max(len(embeddings), 1),
        "n_failures": len(failures),
    }


musicnn_timing = []
for split in ["train", "val", "test"]:
    musicnn_timing.append(extract_musicnn_split(tracks_df, split))

pd.DataFrame(musicnn_timing)

musicnn:train:   0%|          | 0/677 [00:00<?, ?it/s]

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:58: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  normalized_input = tf.compat.v1.layers.batch_normalization(expand_input, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:103: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:108: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:109: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:117: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:122: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:123: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:135: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv1 = tf.compat.v1.layers.conv2d(inputs=front_end_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:140: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv1 = tf.compat.v1.layers.batch_normalization(conv1, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:145: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv2 = tf.compat.v1.layers.conv2d(inputs=bn_conv1_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:150: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv2 = tf.compat.v1.layers.batch_normalization(conv2, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:156: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv3 = tf.compat.v1.layers.conv2d(inputs=bn_conv2_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:161: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv3 = tf.compat.v1.layers.batch_normalization(conv3, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:176: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  flat_pool = tf.compat.v1.layers.flatten(tmp_pool)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:177: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  flat_pool = tf.compat.v1.layers.batch_normalization(flat_pool, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:178: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  flat_pool_dropout = tf.compat.v1.layers.dropout(flat_pool, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:179: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  dense = tf.compat.v1.layers.dense(inputs=flat_pool_dropout,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:182: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_dense = tf.compat.v1.layers.batch_normalization(dense, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:183: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  dense_dropout = tf.compat.v1.layers.dropout(bn_dense, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:186: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  logits = tf.compat.v1.layers.dense(inputs=dense_dropout,
2026-07-11 19:32:25.363002: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 1/677 [00:03<40:02,  3.55s/it]

done!

/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:58: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  normalized_input = tf.compat.v1.layers.batch_normalization(expand_input, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:103: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:108: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:109: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:117: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv = tf.compat.v1.layers.conv2d(inputs=inputs,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:122: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv = tf.compat.v1.layers.batch_normalization(conv, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:123: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  pool = tf.compat.v1.layers.max_pooling2d(inputs=bn_conv,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:135: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv1 = tf.compat.v1.layers.conv2d(inputs=front_end_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:140: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv1 = tf.compat.v1.layers.batch_normalization(conv1, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:145: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv2 = tf.compat.v1.layers.conv2d(inputs=bn_conv1_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:150: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv2 = tf.compat.v1.layers.batch_normalization(conv2, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:156: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  conv3 = tf.compat.v1.layers.conv2d(inputs=bn_conv2_pad,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:161: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_conv3 = tf.compat.v1.layers.batch_normalization(conv3, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:176: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  flat_pool = tf.compat.v1.layers.flatten(tmp_pool)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:177: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  flat_pool = tf.compat.v1.layers.batch_normalization(flat_pool, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:178: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  flat_pool_dropout = tf.compat.v1.layers.dropout(flat_pool, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:179: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  dense = tf.compat.v1.layers.dense(inputs=flat_pool_dropout,
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:182: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  bn_dense = tf.compat.v1.layers.batch_normalization(dense, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:183: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.
  dense_dropout = tf.compat.v1.layers.dropout(bn_dense, rate=0.5, training=is_training)
/home/winni/miniconda3/envs/rhythmx_embed/lib/python3.10/site-packages/musicnn/models.py:186: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  logits = tf.compat.v1.layers.dense(inputs=dense_dropout,

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 2/677 [00:05<29:57,  2.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   0%|          | 3/677 [00:07<26:27,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 4/677 [00:09<24:38,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 5/677 [00:11<23:56,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 6/677 [00:13<23:29,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 7/677 [00:15<24:31,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|          | 8/677 [00:18<23:52,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|▏         | 9/677 [00:20<23:25,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   1%|▏         | 10/677 [00:22<23:07,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 11/677 [00:24<22:49,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 12/677 [00:26<22:32,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 13/677 [00:28<22:17,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 14/677 [00:30<22:10,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 15/677 [00:32<22:23,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   2%|▏         | 16/677 [00:34<22:51,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 17/677 [00:36<23:52,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 18/677 [00:38<23:50,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 19/677 [00:41<26:33,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 20/677 [00:44<26:28,  2.42s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 21/677 [00:46<26:50,  2.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 22/677 [00:48<25:59,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   3%|▎         | 23/677 [00:51<25:23,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▎         | 24/677 [00:53<24:47,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▎         | 25/677 [00:55<23:52,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 26/677 [00:57<23:27,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 27/677 [00:59<23:18,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 28/677 [01:01<23:34,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 29/677 [01:04<23:48,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   4%|▍         | 30/677 [01:06<25:42,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 31/677 [01:09<24:59,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 32/677 [01:11<25:23,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▍         | 33/677 [01:13<25:00,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 34/677 [01:16<25:09,  2.35s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 35/677 [01:18<25:08,  2.35s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 36/677 [01:20<25:14,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   5%|▌         | 37/677 [01:23<25:23,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 38/677 [01:25<25:09,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 39/677 [01:28<25:06,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 40/677 [01:30<25:02,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 41/677 [01:32<24:26,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▌         | 42/677 [01:35<26:08,  2.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▋         | 43/677 [01:37<24:55,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   6%|▋         | 44/677 [01:39<23:53,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 45/677 [01:41<23:06,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 46/677 [01:43<22:40,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 47/677 [01:45<22:17,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 48/677 [01:47<21:44,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 49/677 [01:49<21:35,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   7%|▋         | 50/677 [01:51<21:20,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 51/677 [01:53<21:07,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 52/677 [01:55<20:54,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 53/677 [01:58<22:37,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 54/677 [02:00<21:59,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 55/677 [02:02<21:50,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 56/677 [02:04<21:13,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   8%|▊         | 57/677 [02:06<21:02,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▊         | 58/677 [02:08<20:46,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▊         | 59/677 [02:10<20:32,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 60/677 [02:12<20:18,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 61/677 [02:13<20:05,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 62/677 [02:15<20:12,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 63/677 [02:17<20:16,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:   9%|▉         | 64/677 [02:19<20:14,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 65/677 [02:22<22:01,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 66/677 [02:24<21:54,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|▉         | 67/677 [02:26<22:00,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 68/677 [02:28<21:50,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 69/677 [02:31<21:49,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 70/677 [02:33<21:48,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  10%|█         | 71/677 [02:35<21:33,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 72/677 [02:37<21:25,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 73/677 [02:39<21:15,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 74/677 [02:41<21:10,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 75/677 [02:43<21:03,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█         | 76/677 [02:45<21:06,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  11%|█▏        | 77/677 [02:48<22:39,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 78/677 [02:50<22:06,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 79/677 [02:52<21:55,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 80/677 [02:54<21:51,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 81/677 [02:57<21:27,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 82/677 [02:59<21:12,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 83/677 [03:01<21:04,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  12%|█▏        | 84/677 [03:03<20:55,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 85/677 [03:05<20:35,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 86/677 [03:07<20:29,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 87/677 [03:09<20:27,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 88/677 [03:12<22:13,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 89/677 [03:14<21:44,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 90/677 [03:16<21:16,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  13%|█▎        | 91/677 [03:18<21:12,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▎        | 92/677 [03:20<21:05,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▎        | 93/677 [03:22<21:18,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 94/677 [03:25<21:54,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 95/677 [03:27<21:58,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 96/677 [03:29<21:37,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 97/677 [03:31<21:12,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  14%|█▍        | 98/677 [03:33<21:02,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 99/677 [03:36<20:47,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 100/677 [03:38<22:06,  2.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▍        | 101/677 [03:40<21:32,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 102/677 [03:42<21:03,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 103/677 [03:45<20:54,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  15%|█▌        | 104/677 [03:47<20:38,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 105/677 [03:49<20:22,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 106/677 [03:51<20:34,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 107/677 [03:53<20:12,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 108/677 [03:55<20:01,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 109/677 [03:57<19:32,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▌        | 110/677 [03:59<19:18,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  16%|█▋        | 111/677 [04:02<20:48,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 112/677 [04:04<20:09,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 113/677 [04:06<20:12,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 114/677 [04:08<20:08,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 115/677 [04:10<19:53,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 116/677 [04:12<19:52,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 117/677 [04:14<19:37,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  17%|█▋        | 118/677 [04:16<19:36,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 119/677 [04:18<19:30,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 120/677 [04:20<19:27,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 121/677 [04:23<19:17,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 122/677 [04:25<19:30,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 123/677 [04:27<21:14,  2.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 124/677 [04:30<21:00,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  18%|█▊        | 125/677 [04:32<20:27,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▊        | 126/677 [04:34<20:04,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 127/677 [04:36<19:47,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 128/677 [04:38<19:34,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 129/677 [04:40<19:30,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 130/677 [04:42<19:25,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 131/677 [04:45<19:34,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  19%|█▉        | 132/677 [04:46<19:02,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 133/677 [04:49<19:01,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 134/677 [04:51<19:00,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|█▉        | 135/677 [04:53<20:31,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 136/677 [04:56<20:12,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 137/677 [04:58<20:27,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  20%|██        | 138/677 [05:00<20:18,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 139/677 [05:02<20:08,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 140/677 [05:04<19:46,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 141/677 [05:07<19:28,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 142/677 [05:09<19:15,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██        | 143/677 [05:11<19:06,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██▏       | 144/677 [05:13<19:00,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  21%|██▏       | 145/677 [05:15<18:48,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 146/677 [05:17<18:36,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 147/677 [05:20<20:18,  2.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 148/677 [05:22<19:53,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 149/677 [05:24<19:37,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 150/677 [05:26<19:44,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 151/677 [05:28<19:15,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  22%|██▏       | 152/677 [05:31<19:06,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 153/677 [05:33<18:54,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 154/677 [05:35<18:39,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 155/677 [05:37<18:12,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 156/677 [05:39<18:23,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 157/677 [05:41<18:21,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 158/677 [05:44<19:58,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  23%|██▎       | 159/677 [05:46<19:42,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▎       | 160/677 [05:48<19:10,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 161/677 [05:50<19:15,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 162/677 [05:53<19:22,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 163/677 [05:55<19:09,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 164/677 [05:57<19:01,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  24%|██▍       | 165/677 [05:59<18:44,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 166/677 [06:01<18:36,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 167/677 [06:03<18:13,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 168/677 [06:06<17:57,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▍       | 169/677 [06:08<18:00,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 170/677 [06:11<19:46,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 171/677 [06:13<19:37,  2.33s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  25%|██▌       | 172/677 [06:15<19:16,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 173/677 [06:17<18:50,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 174/677 [06:19<18:33,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 175/677 [06:21<18:19,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 176/677 [06:24<18:29,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▌       | 177/677 [06:26<18:22,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▋       | 178/677 [06:28<18:32,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  26%|██▋       | 179/677 [06:30<18:06,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 180/677 [06:32<18:08,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 181/677 [06:35<17:43,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 182/677 [06:37<19:00,  2.30s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 183/677 [06:39<18:31,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 184/677 [06:41<18:09,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 185/677 [06:44<17:50,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  27%|██▋       | 186/677 [06:46<17:30,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 187/677 [06:48<17:21,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 188/677 [06:50<17:17,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 189/677 [06:52<17:09,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 190/677 [06:54<17:17,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 191/677 [06:56<17:26,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  28%|██▊       | 192/677 [06:58<17:17,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▊       | 193/677 [07:01<18:37,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▊       | 194/677 [07:03<18:05,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 195/677 [07:05<17:33,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 196/677 [07:07<17:23,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 197/677 [07:09<17:15,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 198/677 [07:12<17:22,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  29%|██▉       | 199/677 [07:14<17:20,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 200/677 [07:16<17:01,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 201/677 [07:18<16:48,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 202/677 [07:20<16:40,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|██▉       | 203/677 [07:22<17:08,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 204/677 [07:25<17:18,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 205/677 [07:27<18:31,  2.36s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  30%|███       | 206/677 [07:29<17:56,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 207/677 [07:32<17:52,  2.28s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 208/677 [07:34<17:24,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 209/677 [07:36<17:05,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 210/677 [07:38<16:41,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███       | 211/677 [07:40<16:34,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███▏      | 212/677 [07:42<16:35,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  31%|███▏      | 213/677 [07:44<16:31,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 214/677 [07:47<16:32,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 215/677 [07:49<16:21,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 216/677 [07:51<17:24,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 217/677 [07:53<17:02,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 218/677 [07:55<16:41,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 219/677 [07:57<16:15,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  32%|███▏      | 220/677 [08:00<16:07,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 221/677 [08:02<16:00,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 222/677 [08:04<15:36,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 223/677 [08:05<15:14,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 224/677 [08:08<15:14,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 225/677 [08:10<15:20,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  33%|███▎      | 226/677 [08:12<15:09,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▎      | 227/677 [08:14<14:57,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▎      | 228/677 [08:16<16:26,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 229/677 [08:18<15:54,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 230/677 [08:20<15:41,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 231/677 [08:22<15:27,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 232/677 [08:24<15:17,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  34%|███▍      | 233/677 [08:26<15:36,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 234/677 [08:29<15:41,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 235/677 [08:31<15:46,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▍      | 236/677 [08:33<15:28,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 237/677 [08:35<15:21,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 238/677 [08:37<15:22,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 239/677 [08:39<15:18,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  35%|███▌      | 240/677 [08:42<16:40,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 241/677 [08:44<16:23,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 242/677 [08:46<15:52,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 243/677 [08:48<15:31,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 244/677 [08:50<15:19,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▌      | 245/677 [08:52<15:05,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▋      | 246/677 [08:54<15:05,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  36%|███▋      | 247/677 [08:56<14:55,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 248/677 [08:58<14:33,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 249/677 [09:00<14:24,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 250/677 [09:02<14:22,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 251/677 [09:05<15:42,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 252/677 [09:07<15:25,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  37%|███▋      | 253/677 [09:09<15:15,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 254/677 [09:11<15:16,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 255/677 [09:13<14:53,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 256/677 [09:15<14:49,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 257/677 [09:17<14:41,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 258/677 [09:20<14:34,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 259/677 [09:22<14:36,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  38%|███▊      | 260/677 [09:24<14:25,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▊      | 261/677 [09:26<14:20,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▊      | 262/677 [09:28<14:16,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 263/677 [09:30<15:18,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 264/677 [09:32<14:49,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 265/677 [09:34<14:28,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 266/677 [09:36<14:17,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  39%|███▉      | 267/677 [09:39<14:23,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 268/677 [09:41<14:02,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 269/677 [09:43<13:55,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|███▉      | 270/677 [09:45<13:56,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 271/677 [09:47<13:55,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 272/677 [09:49<13:58,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 273/677 [09:51<13:52,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  40%|████      | 274/677 [09:53<14:55,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 275/677 [09:56<15:00,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 276/677 [09:58<14:43,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 277/677 [10:00<14:39,  2.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 278/677 [10:02<14:20,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████      | 279/677 [10:04<14:04,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  41%|████▏     | 280/677 [10:06<13:54,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 281/677 [10:08<14:02,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 282/677 [10:10<13:58,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 283/677 [10:12<13:42,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 284/677 [10:15<13:34,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 285/677 [10:17<13:31,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 286/677 [10:19<14:24,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  42%|████▏     | 287/677 [10:21<13:55,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 288/677 [10:23<13:32,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 289/677 [10:25<13:35,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 290/677 [10:27<13:28,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 291/677 [10:29<13:34,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 292/677 [10:32<13:33,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 293/677 [10:34<13:22,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  43%|████▎     | 294/677 [10:36<13:13,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▎     | 295/677 [10:38<13:01,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▎     | 296/677 [10:40<12:57,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 297/677 [10:42<12:56,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 298/677 [10:44<13:56,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 299/677 [10:46<13:33,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 300/677 [10:48<13:05,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  44%|████▍     | 301/677 [10:50<12:47,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 302/677 [10:52<12:37,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 303/677 [10:54<12:34,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▍     | 304/677 [10:56<12:56,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 305/677 [10:58<12:57,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 306/677 [11:01<12:52,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 307/677 [11:03<13:04,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  45%|████▌     | 308/677 [11:05<12:43,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 309/677 [11:07<12:45,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 310/677 [11:09<13:40,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 311/677 [11:11<13:16,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 312/677 [11:13<13:00,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▌     | 313/677 [11:16<12:51,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  46%|████▋     | 314/677 [11:18<12:39,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 315/677 [11:20<12:33,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 316/677 [11:22<12:30,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 317/677 [11:24<12:30,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 318/677 [11:26<12:29,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 319/677 [11:28<12:14,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 320/677 [11:30<12:05,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  47%|████▋     | 321/677 [11:32<12:47,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 322/677 [11:34<12:20,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 323/677 [11:36<12:07,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 324/677 [11:38<11:54,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 325/677 [11:40<11:39,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 326/677 [11:42<11:37,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 327/677 [11:44<11:42,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  48%|████▊     | 328/677 [11:46<11:55,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▊     | 329/677 [11:48<11:55,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▊     | 330/677 [11:50<11:56,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 331/677 [11:53<12:06,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 332/677 [11:55<11:45,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 333/677 [11:57<12:28,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 334/677 [11:59<12:05,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  49%|████▉     | 335/677 [12:01<11:41,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 336/677 [12:03<11:27,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 337/677 [12:05<11:18,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|████▉     | 338/677 [12:07<11:04,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 339/677 [12:09<11:12,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 340/677 [12:11<11:26,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  50%|█████     | 341/677 [12:13<11:26,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 342/677 [12:15<11:22,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 343/677 [12:17<11:15,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 344/677 [12:19<11:15,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 345/677 [12:22<12:17,  2.22s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████     | 346/677 [12:24<12:01,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████▏    | 347/677 [12:26<11:57,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  51%|█████▏    | 348/677 [12:28<11:53,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 349/677 [12:30<11:44,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 350/677 [12:32<11:33,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 351/677 [12:34<11:37,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 352/677 [12:37<11:44,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 353/677 [12:39<11:40,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 354/677 [12:41<11:38,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  52%|█████▏    | 355/677 [12:43<11:38,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 356/677 [12:46<12:22,  2.31s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 357/677 [12:48<12:06,  2.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 358/677 [12:50<11:45,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 359/677 [12:52<11:36,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 360/677 [12:54<11:30,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 361/677 [12:56<11:17,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  53%|█████▎    | 362/677 [12:58<11:15,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▎    | 363/677 [13:01<11:08,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 364/677 [13:03<10:56,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 365/677 [13:05<10:43,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 366/677 [13:07<10:29,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 367/677 [13:09<10:26,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  54%|█████▍    | 368/677 [13:11<11:10,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 369/677 [13:13<11:12,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 370/677 [13:15<11:05,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 371/677 [13:17<10:51,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▍    | 372/677 [13:19<10:37,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 373/677 [13:21<10:24,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 374/677 [13:23<10:24,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  55%|█████▌    | 375/677 [13:26<10:25,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 376/677 [13:28<10:24,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 377/677 [13:30<10:20,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 378/677 [13:32<10:19,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 379/677 [13:34<11:11,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▌    | 380/677 [13:37<10:56,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▋    | 381/677 [13:39<10:47,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  56%|█████▋    | 382/677 [13:41<10:34,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 383/677 [13:43<10:26,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 384/677 [13:45<10:17,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 385/677 [13:47<10:21,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 386/677 [13:49<10:02,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 387/677 [13:51<09:52,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 388/677 [13:53<09:42,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  57%|█████▋    | 389/677 [13:55<09:34,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 390/677 [13:57<09:28,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 391/677 [13:59<10:10,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 392/677 [14:01<09:56,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 393/677 [14:03<09:39,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 394/677 [14:05<09:28,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 395/677 [14:07<09:21,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  58%|█████▊    | 396/677 [14:09<09:15,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▊    | 397/677 [14:11<09:11,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 398/677 [14:13<09:05,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 399/677 [14:15<09:06,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 400/677 [14:17<09:05,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 401/677 [14:19<09:04,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  59%|█████▉    | 402/677 [14:21<09:49,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 403/677 [14:24<09:45,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 404/677 [14:26<09:44,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 405/677 [14:28<09:31,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|█████▉    | 406/677 [14:30<09:26,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 407/677 [14:32<09:15,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 408/677 [14:34<09:06,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  60%|██████    | 409/677 [14:36<08:59,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 410/677 [14:38<08:57,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 411/677 [14:40<08:50,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 412/677 [14:42<08:59,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 413/677 [14:44<09:02,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████    | 414/677 [14:46<09:41,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████▏   | 415/677 [14:49<09:27,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  61%|██████▏   | 416/677 [14:51<09:10,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 417/677 [14:52<08:57,  2.07s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 418/677 [14:55<08:51,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 419/677 [14:57<08:46,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 420/677 [14:58<08:38,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 421/677 [15:00<08:27,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 422/677 [15:02<08:24,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  62%|██████▏   | 423/677 [15:04<08:26,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 424/677 [15:06<08:24,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 425/677 [15:08<08:19,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 426/677 [15:11<09:05,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 427/677 [15:13<08:47,  2.11s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 428/677 [15:15<08:38,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  63%|██████▎   | 429/677 [15:17<08:29,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▎   | 430/677 [15:19<08:21,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▎   | 431/677 [15:21<08:19,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 432/677 [15:23<08:12,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 433/677 [15:25<08:10,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 434/677 [15:27<08:03,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 435/677 [15:29<08:05,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  64%|██████▍   | 436/677 [15:31<08:02,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 437/677 [15:33<07:50,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 438/677 [15:35<08:30,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 439/677 [15:37<08:15,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▍   | 440/677 [15:39<08:03,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 441/677 [15:41<08:03,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 442/677 [15:43<07:56,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  65%|██████▌   | 443/677 [15:45<07:47,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 444/677 [15:47<07:36,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 445/677 [15:49<07:34,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 446/677 [15:51<07:35,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 447/677 [15:53<07:31,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▌   | 448/677 [15:55<07:26,  1.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▋   | 449/677 [15:57<08:03,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  66%|██████▋   | 450/677 [15:59<07:54,  2.09s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 451/677 [16:01<07:44,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 452/677 [16:03<07:36,  2.03s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 453/677 [16:05<07:28,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 454/677 [16:07<07:28,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 455/677 [16:09<07:22,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  67%|██████▋   | 456/677 [16:11<07:18,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 457/677 [16:13<07:16,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 458/677 [16:15<07:06,  1.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 459/677 [16:17<07:05,  1.95s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 460/677 [16:19<07:06,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 461/677 [16:22<07:45,  2.16s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 462/677 [16:24<07:34,  2.12s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  68%|██████▊   | 463/677 [16:26<07:25,  2.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▊   | 464/677 [16:28<07:14,  2.04s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▊   | 465/677 [16:29<07:02,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 466/677 [16:31<07:02,  2.00s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 467/677 [16:33<06:56,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 468/677 [16:35<06:55,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 469/677 [16:37<06:53,  1.99s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  69%|██████▉   | 470/677 [16:39<06:50,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 471/677 [16:41<06:48,  1.98s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 472/677 [16:44<07:18,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|██████▉   | 473/677 [16:48<08:58,  2.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 474/677 [16:50<08:31,  2.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 475/677 [16:52<07:54,  2.35s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 476/677 [16:54<07:46,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  70%|███████   | 477/677 [16:56<07:29,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 478/677 [17:18<27:12,  8.20s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 479/677 [17:21<21:21,  6.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 480/677 [17:23<17:19,  5.27s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 481/677 [17:26<14:36,  4.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████   | 482/677 [17:28<12:46,  3.93s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████▏  | 483/677 [17:32<12:03,  3.73s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  71%|███████▏  | 484/677 [17:35<11:34,  3.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 485/677 [17:38<10:48,  3.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 486/677 [17:40<09:48,  3.08s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 487/677 [17:43<09:04,  2.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 488/677 [17:45<08:49,  2.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 489/677 [17:48<08:30,  2.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  72%|███████▏  | 490/677 [17:50<08:07,  2.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 491/677 [17:53<07:53,  2.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 492/677 [17:55<07:42,  2.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 493/677 [17:57<07:37,  2.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 494/677 [18:00<07:28,  2.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 495/677 [18:02<07:01,  2.32s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 496/677 [18:04<07:10,  2.38s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  73%|███████▎  | 497/677 [18:06<06:42,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▎  | 498/677 [18:08<06:24,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▎  | 499/677 [18:10<06:20,  2.14s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 500/677 [18:12<05:58,  2.02s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 501/677 [18:14<05:45,  1.96s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 502/677 [18:16<05:27,  1.87s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 503/677 [18:18<05:42,  1.97s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  74%|███████▍  | 504/677 [18:20<05:47,  2.01s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 505/677 [18:22<05:54,  2.06s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 506/677 [18:24<05:59,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▍  | 507/677 [18:26<05:57,  2.10s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 508/677 [18:29<06:27,  2.29s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 509/677 [18:31<06:17,  2.25s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 510/677 [18:33<06:09,  2.21s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  75%|███████▌  | 511/677 [18:36<06:09,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 512/677 [18:38<06:00,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 513/677 [18:40<05:56,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 514/677 [18:42<06:05,  2.24s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 515/677 [18:44<05:54,  2.19s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▌  | 516/677 [18:46<05:51,  2.18s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  76%|███████▋  | 517/677 [18:49<05:46,  2.17s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 518/677 [18:51<05:41,  2.15s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 519/677 [18:53<06:09,  2.34s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 520/677 [18:55<05:49,  2.23s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 521/677 [18:57<05:32,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 522/677 [18:59<05:30,  2.13s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 523/677 [19:02<06:04,  2.37s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  77%|███████▋  | 524/677 [19:04<05:45,  2.26s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 525/677 [19:06<05:12,  2.05s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 526/677 [19:08<04:48,  1.91s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 527/677 [19:09<04:30,  1.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 528/677 [19:11<04:14,  1.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 529/677 [19:12<04:03,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 530/677 [19:14<03:56,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  78%|███████▊  | 531/677 [19:16<04:15,  1.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▊  | 532/677 [19:17<04:06,  1.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▊  | 533/677 [19:19<03:58,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 534/677 [19:20<03:49,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 535/677 [19:22<03:43,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 536/677 [19:23<03:38,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 537/677 [19:25<03:34,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  79%|███████▉  | 538/677 [19:26<03:32,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 539/677 [19:28<03:28,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 540/677 [19:29<03:24,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|███████▉  | 541/677 [19:31<03:22,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 542/677 [19:32<03:20,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 543/677 [19:34<03:40,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  80%|████████  | 544/677 [19:36<03:32,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 545/677 [19:37<03:25,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 546/677 [19:39<03:20,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 547/677 [19:40<03:17,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 548/677 [19:42<03:17,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 549/677 [19:43<03:13,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████  | 550/677 [19:45<03:10,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  81%|████████▏ | 551/677 [19:46<03:07,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 552/677 [19:48<03:04,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 553/677 [19:49<03:07,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 554/677 [19:51<03:04,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 555/677 [19:53<03:18,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 556/677 [19:54<03:09,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 557/677 [19:55<03:05,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  82%|████████▏ | 558/677 [19:57<03:00,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 559/677 [19:58<02:56,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 560/677 [20:00<02:54,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 561/677 [20:01<02:52,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 562/677 [20:03<02:49,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 563/677 [20:04<02:47,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 564/677 [20:06<02:46,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  83%|████████▎ | 565/677 [20:07<02:44,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▎ | 566/677 [20:09<02:58,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 567/677 [20:11<02:53,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 568/677 [20:12<02:48,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 569/677 [20:14<02:45,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 570/677 [20:15<02:42,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 571/677 [20:17<02:39,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  84%|████████▍ | 572/677 [20:18<02:36,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 573/677 [20:19<02:34,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 574/677 [20:21<02:33,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▍ | 575/677 [20:22<02:30,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 576/677 [20:24<02:29,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 577/677 [20:25<02:28,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  85%|████████▌ | 578/677 [20:27<02:40,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 579/677 [20:29<02:34,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 580/677 [20:30<02:29,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 581/677 [20:32<02:25,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 582/677 [20:33<02:21,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▌ | 583/677 [20:35<02:19,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▋ | 584/677 [20:36<02:17,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  86%|████████▋ | 585/677 [20:38<02:15,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 586/677 [20:39<02:13,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 587/677 [20:40<02:11,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 588/677 [20:42<02:09,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 589/677 [20:44<02:20,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 590/677 [20:45<02:15,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 591/677 [20:47<02:11,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  87%|████████▋ | 592/677 [20:48<02:07,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 593/677 [20:50<02:05,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 594/677 [20:51<02:04,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 595/677 [20:53<02:01,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 596/677 [20:54<01:59,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 597/677 [20:56<01:57,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 598/677 [20:57<01:55,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  88%|████████▊ | 599/677 [20:58<01:53,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▊ | 600/677 [21:00<01:51,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 601/677 [21:02<02:01,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 602/677 [21:03<01:57,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 603/677 [21:05<01:52,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 604/677 [21:06<01:50,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  89%|████████▉ | 605/677 [21:08<01:48,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 606/677 [21:09<01:46,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 607/677 [21:11<01:43,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 608/677 [21:12<01:41,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|████████▉ | 609/677 [21:13<01:38,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 610/677 [21:15<01:38,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 611/677 [21:16<01:35,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  90%|█████████ | 612/677 [21:18<01:34,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 613/677 [21:20<01:41,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 614/677 [21:21<01:38,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 615/677 [21:23<01:35,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 616/677 [21:24<01:32,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████ | 617/677 [21:26<01:30,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████▏| 618/677 [21:27<01:27,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  91%|█████████▏| 619/677 [21:29<01:25,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 620/677 [21:30<01:23,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 621/677 [21:31<01:22,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 622/677 [21:33<01:20,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 623/677 [21:34<01:19,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 624/677 [21:36<01:25,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 625/677 [21:38<01:21,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  92%|█████████▏| 626/677 [21:39<01:17,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 627/677 [21:41<01:16,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 628/677 [21:42<01:13,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 629/677 [21:44<01:11,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 630/677 [21:45<01:09,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 631/677 [21:47<01:08,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  93%|█████████▎| 632/677 [21:48<01:06,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▎| 633/677 [21:50<01:04,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▎| 634/677 [21:51<01:02,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 635/677 [21:52<01:01,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 636/677 [21:54<01:05,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 637/677 [21:56<01:03,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 638/677 [21:57<01:00,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  94%|█████████▍| 639/677 [21:59<00:58,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 640/677 [22:00<00:55,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 641/677 [22:02<00:54,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 642/677 [22:03<00:52,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▍| 643/677 [22:05<00:50,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 644/677 [22:06<00:48,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 645/677 [22:08<00:46,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  95%|█████████▌| 646/677 [22:09<00:45,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 647/677 [22:11<00:44,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 648/677 [22:13<00:47,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 649/677 [22:14<00:44,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 650/677 [22:16<00:41,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▌| 651/677 [22:17<00:39,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▋| 652/677 [22:18<00:37,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  96%|█████████▋| 653/677 [22:20<00:35,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 654/677 [22:21<00:34,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 655/677 [22:23<00:32,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 656/677 [22:24<00:31,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 657/677 [22:26<00:29,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 658/677 [22:27<00:27,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 659/677 [22:29<00:28,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  97%|█████████▋| 660/677 [22:31<00:26,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 661/677 [22:32<00:24,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 662/677 [22:33<00:22,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 663/677 [22:35<00:20,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 664/677 [22:37<00:19,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 665/677 [22:38<00:19,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  98%|█████████▊| 666/677 [22:40<00:17,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▊| 667/677 [22:42<00:16,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▊| 668/677 [22:43<00:14,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 669/677 [22:45<00:12,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 670/677 [22:46<00:10,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 671/677 [22:48<00:09,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 672/677 [22:49<00:07,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train:  99%|█████████▉| 673/677 [22:51<00:06,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 674/677 [22:52<00:04,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 675/677 [22:54<00:03,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|█████████▉| 676/677 [22:55<00:01,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:train: 100%|██████████| 677/677 [22:57<00:00,  2.03s/it]

done!

musicnn:val:   0%|          | 0/141 [00:00<?, ?it/s]

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   1%|          | 1/141 [00:01<03:23,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   1%|▏         | 2/141 [00:02<03:24,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   2%|▏         | 3/141 [00:04<03:23,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   3%|▎         | 4/141 [00:05<03:21,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   4%|▎         | 5/141 [00:07<03:44,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   4%|▍         | 6/141 [00:09<03:32,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   5%|▍         | 7/141 [00:10<03:26,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   6%|▌         | 8/141 [00:12<03:20,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   6%|▋         | 9/141 [00:13<03:16,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   7%|▋         | 10/141 [00:15<03:13,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   8%|▊         | 11/141 [00:16<03:10,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   9%|▊         | 12/141 [00:17<03:09,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:   9%|▉         | 13/141 [00:19<03:08,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  10%|▉         | 14/141 [00:21<03:11,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  11%|█         | 15/141 [00:22<03:09,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  11%|█▏        | 16/141 [00:24<03:07,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  12%|█▏        | 17/141 [00:25<03:21,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  13%|█▎        | 18/141 [00:27<03:13,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  13%|█▎        | 19/141 [00:28<03:07,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  14%|█▍        | 20/141 [00:30<03:03,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  15%|█▍        | 21/141 [00:31<02:59,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  16%|█▌        | 22/141 [00:33<02:58,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  16%|█▋        | 23/141 [00:34<02:57,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  17%|█▋        | 24/141 [00:36<02:56,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  18%|█▊        | 25/141 [00:37<02:53,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  18%|█▊        | 26/141 [00:39<02:51,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  19%|█▉        | 27/141 [00:40<02:50,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  20%|█▉        | 28/141 [00:42<02:49,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  21%|██        | 29/141 [00:44<03:04,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  21%|██▏       | 30/141 [00:45<02:57,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  22%|██▏       | 31/141 [00:47<02:53,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  23%|██▎       | 32/141 [00:48<02:50,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  23%|██▎       | 33/141 [00:50<02:49,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  24%|██▍       | 34/141 [00:51<02:45,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  25%|██▍       | 35/141 [00:53<02:41,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  26%|██▌       | 36/141 [00:54<02:39,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  26%|██▌       | 37/141 [00:56<02:39,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  27%|██▋       | 38/141 [00:57<02:37,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  28%|██▊       | 39/141 [00:59<02:35,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  28%|██▊       | 40/141 [01:01<02:47,  1.66s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  29%|██▉       | 41/141 [01:03<02:50,  1.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  30%|██▉       | 42/141 [01:05<02:58,  1.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  30%|███       | 43/141 [01:06<02:52,  1.76s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  31%|███       | 44/141 [01:08<02:49,  1.75s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  32%|███▏      | 45/141 [01:10<02:42,  1.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  33%|███▎      | 46/141 [01:11<02:38,  1.67s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  33%|███▎      | 47/141 [01:13<02:32,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  34%|███▍      | 48/141 [01:14<02:27,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  35%|███▍      | 49/141 [01:16<02:24,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  35%|███▌      | 50/141 [01:18<02:25,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  36%|███▌      | 51/141 [01:19<02:21,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  37%|███▋      | 52/141 [01:21<02:30,  1.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  38%|███▊      | 53/141 [01:23<02:24,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  38%|███▊      | 54/141 [01:24<02:19,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  39%|███▉      | 55/141 [01:26<02:14,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  40%|███▉      | 56/141 [01:27<02:10,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  40%|████      | 57/141 [01:29<02:08,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  41%|████      | 58/141 [01:30<02:05,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  42%|████▏     | 59/141 [01:31<02:03,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  43%|████▎     | 60/141 [01:33<02:02,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  43%|████▎     | 61/141 [01:35<02:00,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  44%|████▍     | 62/141 [01:36<01:58,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  45%|████▍     | 63/141 [01:38<02:08,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  45%|████▌     | 64/141 [01:39<02:03,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  46%|████▌     | 65/141 [01:41<01:59,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  47%|████▋     | 66/141 [01:43<01:57,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  48%|████▊     | 67/141 [01:44<01:53,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  48%|████▊     | 68/141 [01:45<01:51,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  49%|████▉     | 69/141 [01:47<01:49,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  50%|████▉     | 70/141 [01:48<01:47,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  50%|█████     | 71/141 [01:50<01:45,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  51%|█████     | 72/141 [01:51<01:43,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  52%|█████▏    | 73/141 [01:53<01:42,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  52%|█████▏    | 74/141 [01:54<01:40,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  53%|█████▎    | 75/141 [01:56<01:49,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  54%|█████▍    | 76/141 [01:58<01:44,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  55%|█████▍    | 77/141 [01:59<01:40,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  55%|█████▌    | 78/141 [02:01<01:38,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  56%|█████▌    | 79/141 [02:02<01:35,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  57%|█████▋    | 80/141 [02:04<01:32,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  57%|█████▋    | 81/141 [02:05<01:31,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  58%|█████▊    | 82/141 [02:07<01:28,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  59%|█████▉    | 83/141 [02:08<01:27,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  60%|█████▉    | 84/141 [02:10<01:26,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  60%|██████    | 85/141 [02:11<01:24,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  61%|██████    | 86/141 [02:13<01:22,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  62%|██████▏   | 87/141 [02:15<01:29,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  62%|██████▏   | 88/141 [02:16<01:24,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  63%|██████▎   | 89/141 [02:18<01:21,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  64%|██████▍   | 90/141 [02:19<01:18,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  65%|██████▍   | 91/141 [02:21<01:16,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  65%|██████▌   | 92/141 [02:22<01:14,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  66%|██████▌   | 93/141 [02:24<01:14,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  67%|██████▋   | 94/141 [02:26<01:11,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  67%|██████▋   | 95/141 [02:27<01:10,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  68%|██████▊   | 96/141 [02:29<01:08,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  69%|██████▉   | 97/141 [02:30<01:06,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  70%|██████▉   | 98/141 [02:32<01:10,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  70%|███████   | 99/141 [02:33<01:07,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  71%|███████   | 100/141 [02:35<01:04,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  72%|███████▏  | 101/141 [02:37<01:02,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  72%|███████▏  | 102/141 [02:38<01:00,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  73%|███████▎  | 103/141 [02:40<00:58,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  74%|███████▍  | 104/141 [02:41<00:56,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  74%|███████▍  | 105/141 [02:43<00:54,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  75%|███████▌  | 106/141 [02:44<00:53,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  76%|███████▌  | 107/141 [02:46<00:51,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  77%|███████▋  | 108/141 [02:47<00:49,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  77%|███████▋  | 109/141 [02:49<00:47,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  78%|███████▊  | 110/141 [02:51<00:51,  1.65s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  79%|███████▊  | 111/141 [02:52<00:48,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  79%|███████▉  | 112/141 [02:54<00:45,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  80%|████████  | 113/141 [02:55<00:43,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  81%|████████  | 114/141 [02:57<00:41,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  82%|████████▏ | 115/141 [02:58<00:39,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  82%|████████▏ | 116/141 [02:59<00:37,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  83%|████████▎ | 117/141 [03:01<00:35,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  84%|████████▎ | 118/141 [03:02<00:34,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  84%|████████▍ | 119/141 [03:04<00:33,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  85%|████████▌ | 120/141 [03:06<00:31,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  86%|████████▌ | 121/141 [03:07<00:29,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  87%|████████▋ | 122/141 [03:09<00:31,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  87%|████████▋ | 123/141 [03:10<00:28,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  88%|████████▊ | 124/141 [03:12<00:26,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  89%|████████▊ | 125/141 [03:13<00:24,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  89%|████████▉ | 126/141 [03:15<00:22,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  90%|█████████ | 127/141 [03:16<00:21,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  91%|█████████ | 128/141 [03:18<00:19,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  91%|█████████▏| 129/141 [03:19<00:18,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  92%|█████████▏| 130/141 [03:21<00:16,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  93%|█████████▎| 131/141 [03:22<00:15,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  94%|█████████▎| 132/141 [03:24<00:13,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  94%|█████████▍| 133/141 [03:26<00:13,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  95%|█████████▌| 134/141 [03:27<00:11,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  96%|█████████▌| 135/141 [03:29<00:09,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  96%|█████████▋| 136/141 [03:30<00:07,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  97%|█████████▋| 137/141 [03:32<00:06,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  98%|█████████▊| 138/141 [03:33<00:04,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  99%|█████████▊| 139/141 [03:35<00:02,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val:  99%|█████████▉| 140/141 [03:36<00:01,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:val: 100%|██████████| 141/141 [03:38<00:00,  1.55s/it]

done!

musicnn:test:   0%|          | 0/153 [00:00<?, ?it/s]

Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   1%|          | 1/153 [00:01<03:55,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   1%|▏         | 2/153 [00:03<03:45,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   2%|▏         | 3/153 [00:04<03:41,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   3%|▎         | 4/153 [00:06<04:10,  1.68s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   3%|▎         | 5/153 [00:07<03:57,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   4%|▍         | 6/153 [00:09<03:50,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   5%|▍         | 7/153 [00:10<03:44,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   5%|▌         | 8/153 [00:12<03:37,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   6%|▌         | 9/153 [00:13<03:34,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   7%|▋         | 10/153 [00:15<03:30,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   7%|▋         | 11/153 [00:16<03:29,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   8%|▊         | 12/153 [00:18<03:27,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   8%|▊         | 13/153 [00:19<03:26,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:   9%|▉         | 14/153 [00:21<03:23,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  10%|▉         | 15/153 [00:22<03:21,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  10%|█         | 16/153 [00:24<03:39,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  11%|█         | 17/153 [00:26<03:35,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  12%|█▏        | 18/153 [00:27<03:28,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  12%|█▏        | 19/153 [00:28<03:23,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  13%|█▎        | 20/153 [00:30<03:21,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  14%|█▎        | 21/153 [00:31<03:18,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  14%|█▍        | 22/153 [00:33<03:15,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  15%|█▌        | 23/153 [00:34<03:12,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  16%|█▌        | 24/153 [00:36<03:08,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  16%|█▋        | 25/153 [00:37<03:07,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  17%|█▋        | 26/153 [00:39<03:05,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  18%|█▊        | 27/153 [00:41<03:19,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  18%|█▊        | 28/153 [00:42<03:14,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  19%|█▉        | 29/153 [00:43<03:09,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  20%|█▉        | 30/153 [00:45<03:05,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  20%|██        | 31/153 [00:46<03:02,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  21%|██        | 32/153 [00:48<03:01,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  22%|██▏       | 33/153 [00:49<02:59,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  22%|██▏       | 34/153 [00:51<02:57,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  23%|██▎       | 35/153 [00:52<02:55,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  24%|██▎       | 36/153 [00:54<02:51,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  24%|██▍       | 37/153 [00:55<02:48,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  25%|██▍       | 38/153 [00:57<02:47,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  25%|██▌       | 39/153 [00:59<03:03,  1.61s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  26%|██▌       | 40/153 [01:00<02:59,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  27%|██▋       | 41/153 [01:02<02:56,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  27%|██▋       | 42/153 [01:03<02:53,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  28%|██▊       | 43/153 [01:05<02:48,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  29%|██▉       | 44/153 [01:06<02:45,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  29%|██▉       | 45/153 [01:08<02:42,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  30%|███       | 46/153 [01:09<02:40,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  31%|███       | 47/153 [01:11<02:37,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  31%|███▏      | 48/153 [01:12<02:37,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  32%|███▏      | 49/153 [01:14<02:35,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  33%|███▎      | 50/153 [01:16<02:46,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  33%|███▎      | 51/153 [01:17<02:41,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  34%|███▍      | 52/153 [01:18<02:36,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  35%|███▍      | 53/153 [01:20<02:32,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  35%|███▌      | 54/153 [01:21<02:28,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  36%|███▌      | 55/153 [01:23<02:27,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  37%|███▋      | 56/153 [01:24<02:25,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  37%|███▋      | 57/153 [01:26<02:22,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  38%|███▊      | 58/153 [01:27<02:21,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  39%|███▊      | 59/153 [01:29<02:18,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  39%|███▉      | 60/153 [01:30<02:17,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  40%|███▉      | 61/153 [01:32<02:17,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  41%|████      | 62/153 [01:34<02:29,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  41%|████      | 63/153 [01:35<02:25,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  42%|████▏     | 64/153 [01:37<02:20,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  42%|████▏     | 65/153 [01:38<02:17,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  43%|████▎     | 66/153 [01:40<02:13,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  44%|████▍     | 67/153 [01:41<02:10,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  44%|████▍     | 68/153 [01:43<02:07,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  45%|████▌     | 69/153 [01:44<02:05,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  46%|████▌     | 70/153 [01:46<02:04,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  46%|████▋     | 71/153 [01:47<02:02,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  47%|████▋     | 72/153 [01:49<02:00,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  48%|████▊     | 73/153 [01:50<01:58,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  48%|████▊     | 74/153 [01:52<02:06,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  49%|████▉     | 75/153 [01:54<02:02,  1.57s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  50%|████▉     | 76/153 [01:55<01:58,  1.54s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  50%|█████     | 77/153 [01:57<01:55,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  51%|█████     | 78/153 [01:58<01:53,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  52%|█████▏    | 79/153 [02:00<01:51,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  52%|█████▏    | 80/153 [02:01<01:48,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  53%|█████▎    | 81/153 [02:02<01:45,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  54%|█████▎    | 82/153 [02:04<01:44,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  54%|█████▍    | 83/153 [02:06<01:48,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  55%|█████▍    | 84/153 [02:07<01:45,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  56%|█████▌    | 85/153 [02:09<01:51,  1.64s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  56%|█████▌    | 86/153 [02:10<01:47,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  57%|█████▋    | 87/153 [02:12<01:43,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  58%|█████▊    | 88/153 [02:13<01:39,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  58%|█████▊    | 89/153 [02:15<01:36,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  59%|█████▉    | 90/153 [02:16<01:34,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  59%|█████▉    | 91/153 [02:18<01:32,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  60%|██████    | 92/153 [02:19<01:29,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  61%|██████    | 93/153 [02:21<01:28,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  61%|██████▏   | 94/153 [02:23<01:41,  1.72s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  62%|██████▏   | 95/153 [02:25<01:39,  1.71s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  63%|██████▎   | 96/153 [02:26<01:36,  1.69s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  63%|██████▎   | 97/153 [02:28<01:40,  1.80s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  64%|██████▍   | 98/153 [02:30<01:33,  1.70s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  65%|██████▍   | 99/153 [02:31<01:27,  1.63s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  65%|██████▌   | 100/153 [02:33<01:24,  1.60s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  66%|██████▌   | 101/153 [02:34<01:22,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  67%|██████▋   | 102/153 [02:36<01:18,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  67%|██████▋   | 103/153 [02:37<01:15,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  68%|██████▊   | 104/153 [02:39<01:13,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  69%|██████▊   | 105/153 [02:40<01:10,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  69%|██████▉   | 106/153 [02:42<01:09,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  70%|██████▉   | 107/153 [02:43<01:07,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  71%|███████   | 108/153 [02:45<01:12,  1.62s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  71%|███████   | 109/153 [02:47<01:09,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  72%|███████▏  | 110/153 [02:48<01:06,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  73%|███████▎  | 111/153 [02:50<01:04,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  73%|███████▎  | 112/153 [02:51<01:01,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  74%|███████▍  | 113/153 [02:52<00:59,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  75%|███████▍  | 114/153 [02:54<00:57,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  75%|███████▌  | 115/153 [02:55<00:55,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  76%|███████▌  | 116/153 [02:57<00:54,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  76%|███████▋  | 117/153 [02:58<00:52,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  77%|███████▋  | 118/153 [03:00<00:50,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  78%|███████▊  | 119/153 [03:01<00:49,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  78%|███████▊  | 120/153 [03:03<00:52,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  79%|███████▉  | 121/153 [03:04<00:49,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  80%|███████▉  | 122/153 [03:06<00:46,  1.51s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  80%|████████  | 123/153 [03:07<00:44,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  81%|████████  | 124/153 [03:09<00:43,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  82%|████████▏ | 125/153 [03:10<00:41,  1.47s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  82%|████████▏ | 126/153 [03:12<00:39,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  83%|████████▎ | 127/153 [03:13<00:37,  1.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  84%|████████▎ | 128/153 [03:15<00:36,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  84%|████████▍ | 129/153 [03:16<00:34,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  85%|████████▍ | 130/153 [03:17<00:33,  1.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  86%|████████▌ | 131/153 [03:19<00:31,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  86%|████████▋ | 132/153 [03:21<00:33,  1.58s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  87%|████████▋ | 133/153 [03:22<00:30,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  88%|████████▊ | 134/153 [03:24<00:29,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  88%|████████▊ | 135/153 [03:25<00:27,  1.52s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  89%|████████▉ | 136/153 [03:27<00:25,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  90%|████████▉ | 137/153 [03:28<00:23,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  90%|█████████ | 138/153 [03:30<00:22,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  91%|█████████ | 139/153 [03:31<00:20,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  92%|█████████▏| 140/153 [03:32<00:18,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  92%|█████████▏| 141/153 [03:34<00:17,  1.44s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  93%|█████████▎| 142/153 [03:35<00:16,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  93%|█████████▎| 143/153 [03:37<00:15,  1.59s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  94%|█████████▍| 144/153 [03:39<00:14,  1.56s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  95%|█████████▍| 145/153 [03:40<00:12,  1.55s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  95%|█████████▌| 146/153 [03:42<00:10,  1.53s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  96%|█████████▌| 147/153 [03:43<00:09,  1.50s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  97%|█████████▋| 148/153 [03:45<00:07,  1.49s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  97%|█████████▋| 149/153 [03:46<00:05,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  98%|█████████▊| 150/153 [03:47<00:04,  1.45s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  99%|█████████▊| 151/153 [03:49<00:02,  1.46s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test:  99%|█████████▉| 152/153 [03:50<00:01,  1.48s/it]

done!
Computing spectrogram (w/ librosa) and tags (w/ tensorflow)..

musicnn:test: 100%|██████████| 153/153 [03:52<00:00,  1.52s/it]

done!

,model,split,n_clips,embedding_dim,total_seconds,seconds_per_clip,n_failures
0,musicnn,train,677,753,1377.515565,2.034735,0
1,musicnn,val,141,753,218.166939,1.547283,0
2,musicnn,test,153,753,232.381675,1.518834,0

## 4. MERT embedding extraction

MERT expects **24 kHz mono audio**, so clips are resampled from GTZAN's native
22.05 kHz. We mean-pool across the time dimension of the last hidden state to get
a clip-level vector. `MERT-v1-330M` outputs 1024-dim embeddings; the smaller
`MERT-v1-95M` outputs 768-dim — swap the `MODEL_NAME` if you're CPU-bound.

In [ ]:
MODEL_NAME = "m-a-p/MERT-v1-95M"   # swap to "m-a-p/MERT-v1-330M" if have GPU for faster extraction
TARGET_SR = 24000

mert_processor = Wav2Vec2FeatureExtractor.from_pretrained(MODEL_NAME, trust_remote_code=True)
mert_model = AutoModel.from_pretrained(MODEL_NAME, trust_remote_code=True).to(DEVICE)
mert_model.eval()


def extract_mert_embedding(file_path):
    """Return a single fixed-length embedding vector for one audio clip."""
    waveform, sr = librosa.load(file_path, sr=TARGET_SR, mono=True)

    inputs = mert_processor(
        waveform, sampling_rate=TARGET_SR, return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = mert_model(**inputs, output_hidden_states=True)

    # Mean-pool the final hidden state over the time dimension
    last_hidden = outputs.hidden_states[-1].squeeze(0)   # (time, hidden_dim)
    embedding = last_hidden.mean(dim=0).cpu().numpy()
    return embedding


def extract_mert_split(df, split_name, out_dir="embeddings"):
    os.makedirs(out_dir, exist_ok=True)
    split_df = df[df["split"] == split_name].reset_index(drop=True)

    embeddings = []
    labels = []
    failures = []
    start = time.time()

    for _, row in tqdm(split_df.iterrows(), total=len(split_df), desc=f"MERT:{split_name}"):
        try:
            emb = extract_mert_embedding(row["file_path"])
            embeddings.append(emb)
            labels.append(row["genre"])
        except Exception as e:
            failures.append((row["file_path"], str(e)))

    elapsed = time.time() - start
    embeddings = np.stack(embeddings)

    np.save(f"{out_dir}/mert_{split_name}.npy", embeddings)
    pd.DataFrame({"genre": labels}).to_csv(
        f"{out_dir}/mert_{split_name}_labels.csv", index=False
    )

    if failures:
        print(f"  {len(failures)} clips failed extraction — see failures list")

    return {
        "model": "mert",
        "split": split_name,
        "n_clips": len(embeddings),
        "embedding_dim": embeddings.shape[1],
        "total_seconds": elapsed,
        "seconds_per_clip": elapsed / max(len(embeddings), 1),
        "n_failures": len(failures),
    }


mert_timing = []
for split in ["train", "val", "test"]:
    mert_timing.append(extract_mert_split(tracks_df, split))

pd.DataFrame(mert_timing)

## 5. Consolidate timing + sanity checks

Save extraction timing for both models — this feeds the cost/latency comparison
table in the Sprint 4 writeup (accuracy isn't the only axis your capstone should
compare on).

In [ ]:
timing_df = pd.DataFrame(musicnn_timing + mert_timing)
os.makedirs("embeddings", exist_ok=True)
timing_df.to_csv("embeddings/extraction_timing.csv", index=False)
timing_df

# Quick sanity check: confirm labels line up across splits/models before moving on
for model in ["musicnn", "mert"]:
    for split in ["train", "val", "test"]:
        emb = np.load(f"embeddings/{model}_{split}.npy")
        lbl = pd.read_csv(f"embeddings/{model}_{split}_labels.csv")
        assert emb.shape[0] == len(lbl), f"Mismatch: {model}/{split}"
        print(f"{model:8s} {split:5s} -> embeddings {emb.shape}, labels {len(lbl)}")

---
**Next step:** open `Sprint4_Comparison_Workflow.md` to train classifier heads on
these embeddings, evaluate against your Sprint 3 CNN test metrics, and build the
final 3-way comparison table.